version: '2'
services:
    server:
        build: .
        ports:
            - "8091:8000"
        volumes:
            - .:/app
        depends_on:
          - db
        restart: always
    db:
      ports:
        - 19432:5432
      environment:
        - POSTGRES_PASSWORD=UltraSecurePass
        - POSTGRES_USER=icargo
        - POSTGRES_DB=icargo
      image: postgres:11
      restart: always
