"""empty message

Revision ID: 08175e97884c
Revises: eff880ff5cac
Create Date: 2022-04-07 15:27:55.308610

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "08175e97884c"
down_revision = "eff880ff5cac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tipo_iva",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("pais_id", sa.Integer(), nullable=True),
        sa.Column("iva", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["pais_id"],
            ["pais.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "factura",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("liquidacion_id", sa.Integer(), nullable=True),
        sa.Column("numero_factura", sa.String(length=255), nullable=True),
        sa.Column("monto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("moneda_id", sa.Integer(), nullable=True),
        sa.Column("iva_id", sa.Integer(), nullable=True),
        sa.Column("fecha_vencimiento", sa.DateTime(), nullable=True),
        sa.Column("foto", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["iva_id"],
            ["tipo_iva.id"],
        ),
        sa.ForeignKeyConstraint(
            ["liquidacion_id"],
            ["liquidacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moneda_id"],
            ["moneda.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("liquidacion_id", "numero_factura", "moneda_id", "iva_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("factura")
    op.drop_table("tipo_iva")
    # ### end Alembic commands ###
