"""empty message

Revision ID: 0855f4f04d18
Revises: f0f2004b8d0d
Create Date: 2021-11-29 16:25:58.713047

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0855f4f04d18"
down_revision = "f0f2004b8d0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("color", sa.Column("color", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("color", "color")
    # ### end Alembic commands ###
