"""empty message

Revision ID: 087aa5f54e43
Revises: 4a47fa0afc9d
Create Date: 2021-11-30 20:11:25.580406

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "087aa5f54e43"
down_revision = "4a47fa0afc9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "camion",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("placa", sa.String(length=255), nullable=True),
        sa.Column("propietario_id", sa.Integer(), nullable=True),
        sa.Column("chofer_id", sa.Integer(), nullable=True),
        sa.Column("numero_chasis", sa.String(length=255), nullable=True),
        sa.Column("foto", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Pendiente", nullable=True
        ),
        sa.Column("ciudad_habilitacion_municipal_id", sa.Integer(), nullable=True),
        sa.Column(
            "numero_habilitacion_municipal", sa.String(length=255), nullable=True
        ),
        sa.Column("vencimiento_habilitacion_municipal", sa.DateTime(), nullable=True),
        sa.Column(
            "foto_habilitacion_municipal_frente", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "foto_habilitacion_municipal_reverso", sa.String(length=255), nullable=True
        ),
        sa.Column("ente_emisor_transporte_id", sa.Integer(), nullable=True),
        sa.Column(
            "numero_habilitacion_transporte", sa.String(length=255), nullable=True
        ),
        sa.Column("vencimiento_habilitacion_transporte", sa.DateTime(), nullable=True),
        sa.Column(
            "foto_habilitacion_transporte_frente", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "foto_habilitacion_transporte_reverso", sa.String(length=255), nullable=True
        ),
        sa.Column("ente_emisor_automotor_id", sa.Integer(), nullable=True),
        sa.Column(
            "titular_habilitacion_automotor", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "foto_habilitacion_automotor_frente", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "foto_habilitacion_automotor_reverso", sa.String(length=255), nullable=True
        ),
        sa.Column("marca_id", sa.Integer(), nullable=True),
        sa.Column("tipo_id", sa.Integer(), nullable=True),
        sa.Column("color_id", sa.Integer(), nullable=True),
        sa.Column("anho", sa.Integer(), nullable=True),
        sa.Column("bruto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("tara", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["chofer_id"],
            ["chofer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ciudad_habilitacion_municipal_id"],
            ["ciudad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["color.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ente_emisor_automotor_id"],
            ["ente_emisor_automotor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ente_emisor_transporte_id"],
            ["ente_emisor_transporte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["marca_id"],
            ["marca_camion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["propietario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["tipo_camion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("placa"),
    )
    op.add_column(
        "ente_emisor_automotor", sa.Column("pais_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "ente_emisor_automotor", "pais", ["pais_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ente_emisor_automotor", type_="foreignkey")
    op.drop_column("ente_emisor_automotor", "pais_id")
    op.drop_table("camion")
    # ### end Alembic commands ###
