"""empty message

Revision ID: 0eee5ca9f4f2
Revises: e0111f8b458a
Create Date: 2022-02-01 20:28:56.285633

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0eee5ca9f4f2"
down_revision = "e0111f8b458a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "orden_carga_anticipo_retirado_flete_anticipo_id_orden_carga_key",
        "orden_carga_anticipo_retirado",
        type_="unique",
    )
    op.create_unique_constraint(
        None,
        "orden_carga_anticipo_retirado",
        [
            "flete_anticipo_id",
            "orden_carga_id",
            "punto_venta_id",
            "tipo_comprobante_id",
            "numero_comprobante",
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orden_carga_anticipo_retirado", type_="unique")
    op.create_unique_constraint(
        "orden_carga_anticipo_retirado_flete_anticipo_id_orden_carga_key",
        "orden_carga_anticipo_retirado",
        ["flete_anticipo_id", "orden_carga_id", "punto_venta_id"],
    )
    # ### end Alembic commands ###
