"""empty message

Revision ID: 0f28d85af9de
Revises: 1c90eddb7aba
Create Date: 2022-06-10 21:02:38.024197

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f28d85af9de"
down_revision = "1c90eddb7aba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "estado")
    # ### end Alembic commands ###
