"""empty message

Revision ID: 13ee7d16b422
Revises: d7c784d9c284
Create Date: 2021-11-12 01:47:12.638813

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "13ee7d16b422"
down_revision = "d7c784d9c284"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "remitente", sa.Column("info_complementaria", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("remitente", "info_complementaria")
    # ### end Alembic commands ###
