"""empty message

Revision ID: 17656ae9f551
Revises: fc7b2d1d1f1e
Create Date: 2022-02-17 16:27:26.018674

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "17656ae9f551"
down_revision = "fc7b2d1d1f1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "orden_carga_complemento_concepto_id_propietario_moneda_id_p_key",
        "orden_carga_complemento",
        type_="unique",
    )
    op.drop_constraint(
        "orden_carga_descuento_concepto_id_propietario_moneda_id_pro_key",
        "orden_carga_descuento",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "orden_carga_descuento_concepto_id_propietario_moneda_id_pro_key",
        "orden_carga_descuento",
        [
            "concepto_id",
            "propietario_moneda_id",
            "propietario_monto",
            "proveedor_moneda_id",
            "proveedor_monto",
            "orden_carga_id",
        ],
    )
    op.create_unique_constraint(
        "orden_carga_complemento_concepto_id_propietario_moneda_id_p_key",
        "orden_carga_complemento",
        [
            "concepto_id",
            "propietario_moneda_id",
            "propietario_monto",
            "remitente_moneda_id",
            "remitente_monto",
            "orden_carga_id",
        ],
    )
    # ### end Alembic commands ###
