"""empty message

Revision ID: 1a0dc4c2206a
Revises: 7ed401e7b996
Create Date: 2022-08-16 17:15:57.647818

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1a0dc4c2206a"
down_revision = "7ed401e7b996"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "orden_carga_anticipo_retirado_flete_anticipo_id_orden_carga_key",
        "orden_carga_anticipo_retirado",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "orden_carga_anticipo_retirado_flete_anticipo_id_orden_carga_key",
        "orden_carga_anticipo_retirado",
        [
            "flete_anticipo_id",
            "orden_carga_id",
            "punto_venta_id",
            "tipo_comprobante_id",
            "numero_comprobante",
        ],
    )
    # ### end Alembic commands ###
