"""empty message

Revision ID: 1c90eddb7aba
Revises: c28f34015a12
Create Date: 2022-05-18 15:41:53.086939

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1c90eddb7aba"
down_revision = "c28f34015a12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flete_centro_operativo_contacto",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "flete_centro_operativo_contacto",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "flete_centro_operativo_contacto",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "flete_centro_operativo_contacto",
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "flete_centro_operativo_contacto", sa.Column("id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "flete_centro_operativo_contacto",
        "flete_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "flete_centro_operativo_contacto",
        "centro_operativo_contacto_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.add_column(
        "flete_remitente_contacto",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "flete_remitente_contacto",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "flete_remitente_contacto",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "flete_remitente_contacto",
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "flete_remitente_contacto", sa.Column("id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "flete_remitente_contacto",
        "flete_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "flete_remitente_contacto",
        "remitente_contacto_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.add_column(
        "flete_user_contacto",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "flete_user_contacto",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "flete_user_contacto",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "flete_user_contacto",
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column("flete_user_contacto", sa.Column("id", sa.Integer(), nullable=True))
    op.alter_column(
        "flete_user_contacto", "flete_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "flete_user_contacto",
        "user_contacto_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flete_user_contacto",
        "user_contacto_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "flete_user_contacto", "flete_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("flete_user_contacto", "id")
    op.drop_column("flete_user_contacto", "modified_at")
    op.drop_column("flete_user_contacto", "modified_by")
    op.drop_column("flete_user_contacto", "created_at")
    op.drop_column("flete_user_contacto", "created_by")
    op.alter_column(
        "flete_remitente_contacto",
        "remitente_contacto_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "flete_remitente_contacto",
        "flete_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("flete_remitente_contacto", "id")
    op.drop_column("flete_remitente_contacto", "modified_at")
    op.drop_column("flete_remitente_contacto", "modified_by")
    op.drop_column("flete_remitente_contacto", "created_at")
    op.drop_column("flete_remitente_contacto", "created_by")
    op.alter_column(
        "flete_centro_operativo_contacto",
        "centro_operativo_contacto_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "flete_centro_operativo_contacto",
        "flete_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("flete_centro_operativo_contacto", "id")
    op.drop_column("flete_centro_operativo_contacto", "modified_at")
    op.drop_column("flete_centro_operativo_contacto", "modified_by")
    op.drop_column("flete_centro_operativo_contacto", "created_at")
    op.drop_column("flete_centro_operativo_contacto", "created_by")
    # ### end Alembic commands ###
