"""empty message

Revision ID: 1dd01a9a242d
Revises: 13ee7d16b422
Create Date: 2021-11-12 15:36:24.600406

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1dd01a9a242d"
down_revision = "13ee7d16b422"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permiso",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("accion", sa.String(length=255), nullable=True),
        sa.Column("modelo", sa.String(length=255), nullable=True),
        sa.Column(
            "autorizado", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("modelo", "accion", "autorizado"),
    )
    op.create_table(
        "rol_permiso",
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.Column("permiso_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permiso_id"],
            ["permiso.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["rol.id"],
        ),
    )
    op.create_table(
        "user_permiso",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("permiso_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permiso_id"],
            ["permiso.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_permiso")
    op.drop_table("rol_permiso")
    op.drop_table("permiso")
    # ### end Alembic commands ###
