"""empty message

Revision ID: 232894d29c06
Revises: e949534171d8
Create Date: 2022-11-17 14:54:24.273747

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "232894d29c06"
down_revision = "e949534171d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "camion_semi_neto_camion_id_semi_id_producto_id_gestor_carga_key",
        "camion_semi_neto",
        type_="unique",
    )
    op.create_unique_constraint(
        None,
        "camion_semi_neto",
        ["camion_id", "semi_id", "producto_id", "gestor_carga_id", "neto"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "camion_semi_neto", type_="unique")
    op.create_unique_constraint(
        "camion_semi_neto_camion_id_semi_id_producto_id_gestor_carga_key",
        "camion_semi_neto",
        ["camion_id", "semi_id", "producto_id", "gestor_carga_id"],
    )
    # ### end Alembic commands ###
