"""empty message

Revision ID: 2357d82e221d
Revises: 82f988c95231
Create Date: 2021-11-25 20:29:13.136974

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2357d82e221d"
down_revision = "82f988c95231"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chofer",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("tipo_documento_id", sa.Integer(), nullable=True),
        sa.Column("pais_emisor_documento_id", sa.Integer(), nullable=True),
        sa.Column("numero_documento", sa.String(length=255), nullable=True),
        sa.Column("ruc", sa.String(length=255), nullable=True),
        sa.Column("digito_verificador", sa.String(length=2), nullable=True),
        sa.Column("fecha_nacimiento", sa.DateTime(), nullable=True),
        sa.Column("gestor_cuenta_id", sa.Integer(), nullable=True),
        sa.Column("oficial_cuenta_id", sa.Integer(), nullable=True),
        sa.Column("foto_documento_frente", sa.String(length=255), nullable=True),
        sa.Column("foto_documento_reverso", sa.String(length=255), nullable=True),
        sa.Column("foto_perfil", sa.String(length=255), nullable=True),
        sa.Column(
            "es_propietario",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("ciudad_emisor_registro_id", sa.Integer(), nullable=True),
        sa.Column("tipo_registro_id", sa.Integer(), nullable=True),
        sa.Column("numero_registro", sa.String(length=255), nullable=True),
        sa.Column("vencimiento_registro", sa.DateTime(), nullable=True),
        sa.Column("foto_registro_frente", sa.String(length=255), nullable=True),
        sa.Column("foto_registro_reverso", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Pendiente", nullable=True
        ),
        sa.Column("telefono", sa.String(length=25), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("ciudad_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ciudad_emisor_registro_id"],
            ["ciudad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ciudad_id"],
            ["ciudad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_cuenta_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["oficial_cuenta_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pais_emisor_documento_id"],
            ["pais.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_documento_id"],
            ["tipo_documento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_registro_id"],
            ["tipo_registro.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tipo_documento_id", "pais_emisor_documento_id", "numero_documento"
        ),
    )
    op.create_table(
        "gestor_carga_chofer",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chofer_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["chofer_id"],
            ["chofer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chofer_id", "gestor_carga_id"),
    )
    op.add_column("propietario", sa.Column("chofer_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "propietario", "chofer", ["chofer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "propietario", type_="foreignkey")
    op.drop_column("propietario", "chofer_id")
    op.drop_table("gestor_carga_chofer")
    op.drop_table("chofer")
    # ### end Alembic commands ###
