"""empty message

Revision ID: 242c2281fb07
Revises: 5e5aacd12e66
Create Date: 2021-12-16 03:27:47.638692

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "242c2281fb07"
down_revision = "5e5aacd12e66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flete",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("remitente_id", sa.Integer(), nullable=True),
        sa.Column("producto_id", sa.Integer(), nullable=True),
        sa.Column("tipo_carga_id", sa.Integer(), nullable=True),
        sa.Column("numero_factura", sa.String(length=255), nullable=True),
        sa.Column("numero_crt", sa.String(length=255), nullable=True),
        sa.Column("gestor_cuenta_id", sa.Integer(), nullable=True),
        sa.Column(
            "publicado", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "es_subasta", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("saldo", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("origen_id", sa.Integer(), nullable=True),
        sa.Column("origen_indicacion", sa.Text(), nullable=True),
        sa.Column("destino_id", sa.Integer(), nullable=True),
        sa.Column("destino_indicacion", sa.Text(), nullable=True),
        sa.Column("distancia", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column(
            "condicion_cantidad", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("condicion_gestor_cuenta_moneda_id", sa.Integer(), nullable=True),
        sa.Column(
            "condicion_gestor_cuenta_tarifa",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
        sa.Column("condicion_gestor_cuenta_unidad_id", sa.Integer(), nullable=True),
        sa.Column("condicion_propietario_moneda_id", sa.Integer(), nullable=True),
        sa.Column(
            "condicion_propietario_tarifa",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
        sa.Column("condicion_propietario_unidad_id", sa.Integer(), nullable=True),
        sa.Column(
            "merma_gestor_cuenta_valor",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
        sa.Column("merma_gestor_cuenta_moneda_id", sa.Integer(), nullable=True),
        sa.Column("merma_gestor_cuenta_unidad_id", sa.Integer(), nullable=True),
        sa.Column(
            "merma_gestor_cuenta_es_porcentual",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "merma_gestor_cuenta_tolerancia",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
        sa.Column(
            "merma_propietario_valor", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("merma_propietario_moneda_id", sa.Integer(), nullable=True),
        sa.Column("merma_propietario_unidad_id", sa.Integer(), nullable=True),
        sa.Column(
            "merma_propietario_es_porcentual",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "merma_propietario_tolerancia",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
        sa.Column("vigencia_anticipos", sa.DateTime(), nullable=True),
        sa.Column("emision_orden_texto_legal", sa.Text(), nullable=True),
        sa.Column("emision_orden_detalle", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["condicion_gestor_cuenta_moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["condicion_gestor_cuenta_unidad_id"],
            ["unidad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["condicion_propietario_moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["condicion_propietario_unidad_id"],
            ["unidad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destino_id"],
            ["centro_operativo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_cuenta_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merma_gestor_cuenta_moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merma_gestor_cuenta_unidad_id"],
            ["unidad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merma_propietario_moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merma_propietario_unidad_id"],
            ["unidad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origen_id"],
            ["centro_operativo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["producto.id"],
        ),
        sa.ForeignKeyConstraint(
            ["remitente_id"],
            ["remitente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_carga_id"],
            ["tipo_carga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "remitente_id", "producto_id", "tipo_carga_id", "numero_factura"
        ),
    )
    op.create_table(
        "flete_anticipo",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo_id", sa.Integer(), nullable=True),
        sa.Column("porcentaje", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["tipo_anticipo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo_id", "flete_id"),
    )
    op.create_table(
        "flete_centro_operativo_contacto",
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.Column("centro_operativo_contacto_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["centro_operativo_contacto_id"],
            ["centro_operativo_contacto_gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
    )
    op.create_table(
        "flete_complemento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concepto_id", sa.Integer(), nullable=True),
        sa.Column("detalle", sa.Text(), nullable=True),
        sa.Column(
            "habilitar_cobro_remitente",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "anticipado", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "propietario_monto", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("propietario_moneda_id", sa.Integer(), nullable=True),
        sa.Column("remitente_monto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("remitente_moneda_id", sa.Integer(), nullable=True),
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concepto_id"],
            ["tipo_concepto_complemento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["propietario_moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["remitente_moneda_id"],
            ["moneda.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "concepto_id",
            "propietario_moneda_id",
            "propietario_monto",
            "remitente_moneda_id",
            "remitente_monto",
            "flete_id",
        ),
    )
    op.create_table(
        "flete_descuento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concepto_id", sa.Integer(), nullable=True),
        sa.Column("detalle", sa.Text(), nullable=True),
        sa.Column(
            "habilitar_pago_proveedor",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "anticipado", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "propietario_monto", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("propietario_moneda_id", sa.Integer(), nullable=True),
        sa.Column("proveedor_monto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("proveedor_moneda_id", sa.Integer(), nullable=True),
        sa.Column("proveedor_id", sa.Integer(), nullable=True),
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concepto_id"],
            ["tipo_concepto_descuento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["propietario_moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["proveedor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_moneda_id"],
            ["moneda.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "concepto_id",
            "propietario_moneda_id",
            "propietario_monto",
            "proveedor_moneda_id",
            "proveedor_monto",
            "flete_id",
        ),
    )
    op.create_table(
        "flete_remitente_contacto",
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.Column("remitente_contacto_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["remitente_contacto_id"],
            ["remitente_contacto_gestor_carga.id"],
        ),
    )
    op.create_table(
        "flete_user_contacto",
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.Column("user_contacto_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_contacto_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flete_user_contacto")
    op.drop_table("flete_remitente_contacto")
    op.drop_table("flete_descuento")
    op.drop_table("flete_complemento")
    op.drop_table("flete_centro_operativo_contacto")
    op.drop_table("flete_anticipo")
    op.drop_table("flete")
    # ### end Alembic commands ###
