"""empty message

Revision ID: 2c6cc5464b3c
Revises: 6ccbbd61c209
Create Date: 2022-09-13 12:37:53.899649

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2c6cc5464b3c"
down_revision = "6ccbbd61c209"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactional_user",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero_documento", sa.String(length=15), nullable=True),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("apellido", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=25), nullable=True),
        sa.Column("pin", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("punto_venta_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["punto_venta_id"],
            ["punto_venta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactional_user")
    # ### end Alembic commands ###
