"""empty message

Revision ID: 3c141e8fffd4
Revises: 0f28d85af9de
Create Date: 2022-06-22 12:14:30.061075

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3c141e8fffd4"
down_revision = "0f28d85af9de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("permiso", sa.Column("modulo", sa.String(length=255), nullable=True))
    op.add_column(
        "permiso", sa.Column("modelo_titulo", sa.String(length=255), nullable=True)
    )
    op.drop_constraint(
        "permiso_modelo_accion_autorizado_key", "permiso", type_="unique"
    )
    op.create_index(
        "permiso_modulo_modelo_accion_index",
        "permiso",
        ["modulo", "modelo", "accion"],
        unique=False,
    )
    op.create_unique_constraint(None, "permiso", ["modelo", "accion"])
    op.drop_column("permiso", "autorizado")
    op.add_column("rol", sa.Column("gestor_carga_id", sa.Integer(), nullable=True))
    op.drop_constraint("rol_codigo_key", "rol", type_="unique")
    op.create_unique_constraint(None, "rol", ["descripcion", "gestor_carga_id"])
    op.create_foreign_key(None, "rol", "gestor_carga", ["gestor_carga_id"], ["id"])

    op.drop_table("rol_permiso")
    op.create_table(
        "rol_permiso",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.Column("permiso_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["permiso_id"], ["permiso.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rol_id"], ["rol.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rol_id", "permiso_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rol_permiso")
    op.create_table(
        "rol_permiso",
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.Column("permiso_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permiso_id"],
            ["permiso.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["rol.id"],
        ),
    )
    op.drop_constraint(None, "rol", type_="foreignkey")
    op.drop_constraint(None, "rol", type_="unique")
    op.create_unique_constraint("rol_codigo_key", "rol", ["codigo"])
    op.drop_column("rol", "gestor_carga_id")
    op.add_column(
        "permiso",
        sa.Column(
            "autorizado",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "permiso", type_="unique")
    op.drop_index("permiso_modulo_modelo_accion_index", table_name="permiso")
    op.create_unique_constraint(
        "permiso_modelo_accion_autorizado_key",
        "permiso",
        ["modelo", "accion", "autorizado"],
    )
    op.drop_column("permiso", "modelo_titulo")
    op.drop_column("permiso", "modulo")
    # ### end Alembic commands ###
