"""empty message

Revision ID: 4a47fa0afc9d
Revises: 0855f4f04d18
Create Date: 2021-11-29 19:44:25.439393

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4a47fa0afc9d"
down_revision = "0855f4f04d18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tipo_camion", sa.Column("tipo_imagen", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "tipo_semi", sa.Column("tipo_imagen", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tipo_semi", "tipo_imagen")
    op.drop_column("tipo_camion", "tipo_imagen")
    # ### end Alembic commands ###
