"""empty message

Revision ID: 56be6403857d
Revises: 
Create Date: 2021-09-14 18:14:09.092263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56be6403857d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_auth',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('date_hour', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_database',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('row_id', sa.BigInteger(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('date_hour', sa.DateTime(), nullable=True),
    sa.Column('row', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_request',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('date_hour', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('activation_code', sa.String(length=255), nullable=True),
    sa.Column('persist_code', sa.String(length=255), nullable=True),
    sa.Column('reset_password_code', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('activated_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(precision=0), nullable=True),
    sa.Column('is_activated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_guest', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_activity', postgresql.TIMESTAMP(precision=0), nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(precision=0), nullable=True),
    sa.Column('created_ip_address', sa.String(length=255), nullable=True),
    sa.Column('last_ip_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_activation_code'), 'user', ['activation_code'], unique=False)
    op.create_index(op.f('ix_user_reset_password_code'), 'user', ['reset_password_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reset_password_code'), table_name='user')
    op.drop_index(op.f('ix_user_activation_code'), table_name='user')
    op.drop_table('user')
    op.drop_table('audit_request')
    op.drop_table('audit_database')
    op.drop_table('audit_auth')
    # ### end Alembic commands ###
