"""empty message

Revision ID: 5b79625ee9ca
Revises: dbfaf827a6a0
Create Date: 2022-03-25 12:40:11.464327

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5b79625ee9ca"
down_revision = "dbfaf827a6a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "liquidacion",
        sa.Column(
            "etapa", sa.String(length=255), server_default="En Proceso", nullable=True
        ),
    )
    op.add_column("liquidacion", sa.Column("comentarios", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("liquidacion", "comentarios")
    op.drop_column("liquidacion", "etapa")
    # ### end Alembic commands ###
