"""empty message

Revision ID: 5f9a76e66069
Revises: 56be6403857d
Create Date: 2021-09-30 10:59:35.886342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9a76e66069'
down_revision = '56be6403857d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modified_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modified_by')
    # ### end Alembic commands ###
