"""empty message

Revision ID: 608847d71b87
Revises: 56be6403857d
Create Date: 2021-10-11 23:43:31.180829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608847d71b87'
down_revision = '56be6403857d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centro_operativo_clasificacion',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('contacto',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'apellido', 'telefono', 'email')
    )
    op.create_table('pais',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('nombre_corto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_corto')
    )
    op.create_table('localidad',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'pais_id')
    )
    op.create_table('ciudad',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('localidad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['localidad_id'], ['localidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'localidad_id')
    )
    op.create_table('centro_operativo',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('nombre_corto', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.DECIMAL(), nullable=True),
    sa.Column('longitud', sa.DECIMAL(), nullable=True),
    sa.Column('clasificacion_id', sa.Integer(), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.ForeignKeyConstraint(['clasificacion_id'], ['centro_operativo_clasificacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'clasificacion_id', 'ciudad_id')
    )
    op.create_table('centro_operativo_contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centro_operativo_id', sa.Integer(), nullable=True),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_operativo_id'], ['centro_operativo.id'], ),
    sa.ForeignKeyConstraint(['contacto_id'], ['contacto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True))
    op.add_column('user', sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modified_at')
    op.drop_column('user', 'modified_by')
    op.drop_table('centro_operativo_contacto')
    op.drop_table('centro_operativo')
    op.drop_table('ciudad')
    op.drop_table('localidad')
    op.drop_table('pais')
    op.drop_table('contacto')
    op.drop_table('centro_operativo_clasificacion')
    # ### end Alembic commands ###
