"""empty message

Revision ID: 66424f8d4601
Revises: 790322a7b08e
Create Date: 2022-10-04 16:35:13.391976

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "66424f8d4601"
down_revision = "790322a7b08e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tipo_movimiento", sa.Column("cuenta_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "tipo_movimiento_tipo_documento_relacionado_id_fkey",
        "tipo_movimiento",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "tipo_movimiento", "tipo_cuenta", ["cuenta_id"], ["id"])
    op.drop_column("tipo_movimiento", "tipo_documento_relacionado_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tipo_movimiento",
        sa.Column(
            "tipo_documento_relacionado_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "tipo_movimiento", type_="foreignkey")
    op.create_foreign_key(
        "tipo_movimiento_tipo_documento_relacionado_id_fkey",
        "tipo_movimiento",
        "tipo_documento_relacionado",
        ["tipo_documento_relacionado_id"],
        ["id"],
    )
    op.drop_column("tipo_movimiento", "cuenta_id")
    # ### end Alembic commands ###
