"""empty message

Revision ID: 6b6e869e483e
Revises: a61981f13c07
Create Date: 2021-12-30 20:47:38.804943

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6b6e869e483e"
down_revision = "a61981f13c07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tipo_comprobante",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.add_column("producto", sa.Column("tipo_carga_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "producto", "tipo_carga", ["tipo_carga_id"], ["id"])
    op.add_column(
        "unidad", sa.Column("abreviatura", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("unidad", "abreviatura")
    op.drop_constraint(None, "producto", type_="foreignkey")
    op.drop_column("producto", "tipo_carga_id")
    op.drop_table("tipo_comprobante")
    # ### end Alembic commands ###
