"""empty message

Revision ID: 6ccbbd61c209
Revises: 1a0dc4c2206a
Create Date: 2022-09-06 15:10:29.873869

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6ccbbd61c209"
down_revision = "790322a7b08e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("chofer_id", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("propietario_id", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("punto_venta_id", sa.Integer(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.drop_constraint("user_email_key", "user", type_="unique")
    op.create_foreign_key(None, "user", "punto_venta", ["punto_venta_id"], ["id"])
    op.create_foreign_key(None, "user", "chofer", ["chofer_id"], ["id"])
    op.create_foreign_key(None, "user", "propietario", ["propietario_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.create_unique_constraint("user_email_key", "user", ["email"])
    op.drop_column("user", "is_admin")
    op.drop_column("user", "punto_venta_id")
    op.drop_column("user", "propietario_id")
    op.drop_column("user", "chofer_id")
    # ### end Alembic commands ###
