"""empty message

Revision ID: 7408844c8c42
Revises: 087aa5f54e43
Create Date: 2021-12-04 20:53:37.380508

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7408844c8c42"
down_revision = "087aa5f54e43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semi",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("placa", sa.String(length=255), nullable=True),
        sa.Column("propietario_id", sa.Integer(), nullable=True),
        sa.Column("numero_chasis", sa.String(length=255), nullable=True),
        sa.Column("foto", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Pendiente", nullable=True
        ),
        sa.Column("ciudad_habilitacion_municipal_id", sa.Integer(), nullable=True),
        sa.Column(
            "numero_habilitacion_municipal", sa.String(length=255), nullable=True
        ),
        sa.Column("vencimiento_habilitacion_municipal", sa.DateTime(), nullable=True),
        sa.Column(
            "foto_habilitacion_municipal_frente", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "foto_habilitacion_municipal_reverso", sa.String(length=255), nullable=True
        ),
        sa.Column("ente_emisor_transporte_id", sa.Integer(), nullable=True),
        sa.Column(
            "numero_habilitacion_transporte", sa.String(length=255), nullable=True
        ),
        sa.Column("vencimiento_habilitacion_transporte", sa.DateTime(), nullable=True),
        sa.Column(
            "foto_habilitacion_transporte_frente", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "foto_habilitacion_transporte_reverso", sa.String(length=255), nullable=True
        ),
        sa.Column("ente_emisor_automotor_id", sa.Integer(), nullable=True),
        sa.Column(
            "titular_habilitacion_automotor", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "foto_habilitacion_automotor_frente", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "foto_habilitacion_automotor_reverso", sa.String(length=255), nullable=True
        ),
        sa.Column("marca_id", sa.Integer(), nullable=True),
        sa.Column("clasificacion_id", sa.Integer(), nullable=True),
        sa.Column("tipo_id", sa.Integer(), nullable=True),
        sa.Column("tipo_carga_id", sa.Integer(), nullable=True),
        sa.Column("color_id", sa.Integer(), nullable=True),
        sa.Column("anho", sa.Integer(), nullable=True),
        sa.Column("bruto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("tara", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("largo", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("alto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("ancho", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("volumen", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["ciudad_habilitacion_municipal_id"],
            ["ciudad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clasificacion_id"],
            ["semi_clasificacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["color.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ente_emisor_automotor_id"],
            ["ente_emisor_automotor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ente_emisor_transporte_id"],
            ["ente_emisor_transporte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["marca_id"],
            ["marca_semi.id"],
        ),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["propietario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_carga_id"],
            ["tipo_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["tipo_semi.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("placa"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("semi")
    # ### end Alembic commands ###
