"""empty message

Revision ID: 790322a7b08e
Revises: 2c6cc5464b3c
Create Date: 2022-09-19 17:48:38.475276

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "790322a7b08e"
down_revision = "1a0dc4c2206a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "camion",
        sa.Column(
            "total_anticipos_retirados_en_estado_pendiente_o_en_proceso",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "camion", "total_anticipos_retirados_en_estado_pendiente_o_en_proceso"
    )
    # ### end Alembic commands ###
