"""empty message

Revision ID: 7ed401e7b996
Revises: b648f0c92ffa
Create Date: 2022-08-08 16:47:06.047431

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7ed401e7b996"
down_revision = "b648f0c92ffa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "camion",
        sa.Column(
            "limite_cantidad_oc_activas",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=True,
        ),
    )
    op.add_column(
        "camion",
        sa.Column(
            "limite_monto_anticipos", sa.Numeric(precision=38, scale=10), nullable=True
        ),
    )
    op.add_column(
        "chofer",
        sa.Column(
            "puede_recibir_anticipos",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=True,
        ),
    )
    op.add_column(
        "gestor_carga",
        sa.Column(
            "limite_cantidad_oc_activas",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=True,
        ),
    )
    op.add_column(
        "propietario",
        sa.Column(
            "puede_recibir_anticipos",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("propietario", "puede_recibir_anticipos")
    op.drop_column("gestor_carga", "limite_cantidad_oc_activas")
    op.drop_column("chofer", "puede_recibir_anticipos")
    op.drop_column("camion", "limite_monto_anticipos")
    op.drop_column("camion", "limite_cantidad_oc_activas")
    # ### end Alembic commands ###
