"""empty message

Revision ID: 82f988c95231
Revises: 7fc3606e233b
Create Date: 2021-11-25 13:19:58.948346

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "82f988c95231"
down_revision = "7fc3606e233b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "propietario",
        sa.Column("foto_documento_frente", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "propietario",
        sa.Column("foto_documento_reverso", sa.String(length=255), nullable=True),
    )
    op.drop_column("propietario", "foto_documento")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "propietario",
        sa.Column(
            "foto_documento", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("propietario", "foto_documento_reverso")
    op.drop_column("propietario", "foto_documento_frente")
    # ### end Alembic commands ###
