"""empty message

Revision ID: 836f5cae474d
Revises: e912e17117c5
Create Date: 2022-11-21 12:31:48.476736

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "836f5cae474d"
down_revision = "e912e17117c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tipo_cuenta", sa.Column("codigo", sa.String(length=3), nullable=True)
    )
    op.create_unique_constraint(None, "tipo_cuenta", ["codigo"])
    op.add_column(
        "tipo_movimiento", sa.Column("codigo", sa.String(length=2), nullable=True)
    )
    op.create_unique_constraint(None, "tipo_movimiento", ["cuenta_id", "codigo"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tipo_movimiento", type_="unique")
    op.drop_column("tipo_movimiento", "codigo")
    op.drop_constraint(None, "tipo_cuenta", type_="unique")
    op.drop_column("tipo_cuenta", "codigo")
    # ### end Alembic commands ###
