"""empty message

Revision ID: 935f4253de0a
Revises: 1dd01a9a242d
Create Date: 2021-11-18 11:51:51.077275

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "935f4253de0a"
down_revision = "1dd01a9a242d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tipo_persona",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "propietario",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("tipo_persona_id", sa.Integer(), nullable=True),
        sa.Column("ruc", sa.String(length=255), nullable=True),
        sa.Column("digito_verificador", sa.String(length=2), nullable=True),
        sa.Column("pais_origen_id", sa.Integer(), nullable=True),
        sa.Column("fecha_nacimiento", sa.DateTime(), nullable=True),
        sa.Column("gestor_cuenta_id", sa.Integer(), nullable=True),
        sa.Column("oficial_cuenta_id", sa.Integer(), nullable=True),
        sa.Column("foto_documento", sa.String(length=255), nullable=True),
        sa.Column("foto_perfil", sa.String(length=255), nullable=True),
        sa.Column(
            "es_chofer", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "estado", sa.String(length=255), server_default="Pendiente", nullable=True
        ),
        sa.Column("telefono", sa.String(length=25), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("ciudad_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ciudad_id"],
            ["ciudad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_cuenta_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["oficial_cuenta_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pais_origen_id"],
            ["pais.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_persona_id"],
            ["tipo_persona.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo_persona_id", "ruc"),
    )
    op.create_table(
        "gestor_carga_propietario",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("propietario_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["propietario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("propietario_id", "gestor_carga_id"),
    )
    op.create_table(
        "propietario_contacto_gestor_carga",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cargo_id", sa.Integer(), nullable=True),
        sa.Column("propietario_id", sa.Integer(), nullable=True),
        sa.Column("contacto_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["cargo_id"],
            ["cargo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contacto_id"],
            ["contacto.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["propietario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("propietario_id", "contacto_id", "gestor_carga_id"),
    )
    op.add_column(
        "cargo",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "cargo",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "centro_operativo",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "centro_operativo",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "centro_operativo_clasificacion",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "centro_operativo_clasificacion",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "centro_operativo_contacto_gestor_carga",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "centro_operativo_contacto_gestor_carga",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "ciudad",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "ciudad",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "composicion_juridica",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "composicion_juridica",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "contacto",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "contacto",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "gestor_carga",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "gestor_carga",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "gestor_carga_centro_operativo",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "gestor_carga_centro_operativo",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "gestor_carga_proveedor",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "gestor_carga_proveedor",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "gestor_carga_punto_venta",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "gestor_carga_punto_venta",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "gestor_carga_remitente",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "gestor_carga_remitente",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "localidad",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "localidad",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "moneda",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "moneda",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "pais",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "pais",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "permiso",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "permiso",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "proveedor",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "proveedor",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "proveedor_contacto_gestor_carga",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "proveedor_contacto_gestor_carga",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "punto_venta",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "punto_venta",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "punto_venta_contacto_gestor_carga",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "punto_venta_contacto_gestor_carga",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "remitente",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "remitente",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "remitente_contacto_gestor_carga",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "remitente_contacto_gestor_carga",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "rol",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "rol",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "tipo_documento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "tipo_documento",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "created_at")
    op.drop_column("user", "created_by")
    op.drop_column("tipo_documento", "created_at")
    op.drop_column("tipo_documento", "created_by")
    op.drop_column("rol", "created_at")
    op.drop_column("rol", "created_by")
    op.drop_column("remitente_contacto_gestor_carga", "created_at")
    op.drop_column("remitente_contacto_gestor_carga", "created_by")
    op.drop_column("remitente", "created_at")
    op.drop_column("remitente", "created_by")
    op.drop_column("punto_venta_contacto_gestor_carga", "created_at")
    op.drop_column("punto_venta_contacto_gestor_carga", "created_by")
    op.drop_column("punto_venta", "created_at")
    op.drop_column("punto_venta", "created_by")
    op.drop_column("proveedor_contacto_gestor_carga", "created_at")
    op.drop_column("proveedor_contacto_gestor_carga", "created_by")
    op.drop_column("proveedor", "created_at")
    op.drop_column("proveedor", "created_by")
    op.drop_column("permiso", "created_at")
    op.drop_column("permiso", "created_by")
    op.drop_column("pais", "created_at")
    op.drop_column("pais", "created_by")
    op.drop_column("moneda", "created_at")
    op.drop_column("moneda", "created_by")
    op.drop_column("localidad", "created_at")
    op.drop_column("localidad", "created_by")
    op.drop_column("gestor_carga_remitente", "created_at")
    op.drop_column("gestor_carga_remitente", "created_by")
    op.drop_column("gestor_carga_punto_venta", "created_at")
    op.drop_column("gestor_carga_punto_venta", "created_by")
    op.drop_column("gestor_carga_proveedor", "created_at")
    op.drop_column("gestor_carga_proveedor", "created_by")
    op.drop_column("gestor_carga_centro_operativo", "created_at")
    op.drop_column("gestor_carga_centro_operativo", "created_by")
    op.drop_column("gestor_carga", "created_at")
    op.drop_column("gestor_carga", "created_by")
    op.drop_column("contacto", "created_at")
    op.drop_column("contacto", "created_by")
    op.drop_column("composicion_juridica", "created_at")
    op.drop_column("composicion_juridica", "created_by")
    op.drop_column("ciudad", "created_at")
    op.drop_column("ciudad", "created_by")
    op.drop_column("centro_operativo_contacto_gestor_carga", "created_at")
    op.drop_column("centro_operativo_contacto_gestor_carga", "created_by")
    op.drop_column("centro_operativo_clasificacion", "created_at")
    op.drop_column("centro_operativo_clasificacion", "created_by")
    op.drop_column("centro_operativo", "created_at")
    op.drop_column("centro_operativo", "created_by")
    op.drop_column("cargo", "created_at")
    op.drop_column("cargo", "created_by")
    op.drop_table("propietario_contacto_gestor_carga")
    op.drop_table("gestor_carga_propietario")
    op.drop_table("propietario")
    op.drop_table("tipo_persona")
    # ### end Alembic commands ###
