"""empty message

Revision ID: 9de9d3f2b341
Revises: bf0f61533267
Create Date: 2021-11-04 11:57:44.886214

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9de9d3f2b341"
down_revision = "bf0f61533267"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gestor_carga", sa.Column("telefono", sa.String(length=25), nullable=True)
    )
    op.add_column(
        "gestor_carga", sa.Column("email", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gestor_carga", "email")
    op.drop_column("gestor_carga", "telefono")
    # ### end Alembic commands ###
