"""empty message

Revision ID: a528b1b64f94
Revises: cec03d4e5025
Create Date: 2021-10-28 12:05:20.073803

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a528b1b64f94"
down_revision = "cec03d4e5025"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "centro_operativo", sa.Column("telefono", sa.String(length=25), nullable=True)
    )
    op.add_column(
        "centro_operativo", sa.Column("email", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "centro_operativo",
        sa.Column("pagina_web", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "centro_operativo_contacto_gestor_carga",
        sa.Column("alias", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("centro_operativo_contacto_gestor_carga", "alias")
    op.drop_column("centro_operativo", "pagina_web")
    op.drop_column("centro_operativo", "email")
    op.drop_column("centro_operativo", "telefono")
    # ### end Alembic commands ###
