"""empty message

Revision ID: b648f0c92ffa
Revises: fa8f263a0ca6
Create Date: 2022-07-22 13:08:03.369482

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b648f0c92ffa"
down_revision = "fa8f263a0ca6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orden_carga",
        sa.Column(
            "modify_by_movimiento",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column("condicion_gestor_carga_moneda_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "condicion_gestor_carga_tarifa",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column("condicion_propietario_moneda_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "condicion_propietario_tarifa",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "merma_gestor_carga_valor",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column("merma_gestor_carga_moneda_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "merma_gestor_carga_es_porcentual",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "merma_gestor_carga_tolerancia",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "merma_propietario_valor", sa.Numeric(precision=38, scale=10), nullable=True
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column("merma_propietario_moneda_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "merma_propietario_es_porcentual",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "merma_propietario_tolerancia",
            sa.Numeric(precision=38, scale=10),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None, "orden_carga", "moneda", ["condicion_gestor_carga_moneda_id"], ["id"]
    )
    op.create_foreign_key(
        None, "orden_carga", "moneda", ["condicion_propietario_moneda_id"], ["id"]
    )
    op.create_foreign_key(
        None, "orden_carga", "moneda", ["merma_gestor_carga_moneda_id"], ["id"]
    )
    op.create_foreign_key(
        None, "orden_carga", "moneda", ["merma_propietario_moneda_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orden_carga", type_="foreignkey")
    op.drop_constraint(None, "orden_carga", type_="foreignkey")
    op.drop_constraint(None, "orden_carga", type_="foreignkey")
    op.drop_constraint(None, "orden_carga", type_="foreignkey")
    op.drop_column("orden_carga", "merma_propietario_tolerancia")
    op.drop_column("orden_carga", "merma_propietario_es_porcentual")
    op.drop_column("orden_carga", "merma_propietario_moneda_id")
    op.drop_column("orden_carga", "merma_propietario_valor")
    op.drop_column("orden_carga", "merma_gestor_carga_tolerancia")
    op.drop_column("orden_carga", "merma_gestor_carga_es_porcentual")
    op.drop_column("orden_carga", "merma_gestor_carga_moneda_id")
    op.drop_column("orden_carga", "merma_gestor_carga_valor")
    op.drop_column("orden_carga", "condicion_propietario_tarifa")
    op.drop_column("orden_carga", "condicion_propietario_moneda_id")
    op.drop_column("orden_carga", "condicion_gestor_carga_tarifa")
    op.drop_column("orden_carga", "condicion_gestor_carga_moneda_id")
    op.drop_column("orden_carga", "modify_by_movimiento")
    # ### end Alembic commands ###
