"""empty message

Revision ID: bf0f61533267
Revises: a528b1b64f94
Create Date: 2021-11-01 15:26:32.889603

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bf0f61533267"
down_revision = "a528b1b64f94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "remitente",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("nombre_corto", sa.String(length=255), nullable=True),
        sa.Column("tipo_documento_id", sa.Integer(), nullable=True),
        sa.Column("numero_documento", sa.String(length=255), nullable=True),
        sa.Column("digito_verificador", sa.String(length=2), nullable=True),
        sa.Column("composicion_juridica_id", sa.Integer(), nullable=True),
        sa.Column("logo", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("telefono", sa.String(length=25), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("pagina_web", sa.String(length=255), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("latitud", sa.DECIMAL(), nullable=True),
        sa.Column("longitud", sa.DECIMAL(), nullable=True),
        sa.Column("ciudad_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ciudad_id"],
            ["ciudad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["composicion_juridica_id"],
            ["composicion_juridica.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_documento_id"],
            ["tipo_documento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo_documento_id", "numero_documento"),
    )
    op.create_table(
        "gestor_carga_remitente",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("remitente_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["remitente_id"],
            ["remitente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("remitente_id", "gestor_carga_id"),
    )
    op.create_table(
        "remitente_contacto_gestor_carga",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cargo_id", sa.Integer(), nullable=True),
        sa.Column("remitente_id", sa.Integer(), nullable=True),
        sa.Column("contacto_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["cargo_id"],
            ["cargo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contacto_id"],
            ["contacto.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["remitente_id"],
            ["remitente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("remitente_id", "contacto_id", "gestor_carga_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("remitente_contacto_gestor_carga")
    op.drop_table("gestor_carga_remitente")
    op.drop_table("remitente")
    # ### end Alembic commands ###
