"""empty message

Revision ID: c1c7f37ac666
Revises: 6b6e869e483e
Create Date: 2022-01-11 11:58:50.471384

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c1c7f37ac666"
down_revision = "6b6e869e483e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tipo_insumo",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "insumo",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("tipo_id", sa.Integer(), nullable=True),
        sa.Column("unidad_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["tipo_insumo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unidad_id"],
            ["unidad.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "insumo_punto_venta",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insumo_id", sa.Integer(), nullable=True),
        sa.Column("punto_venta_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("moneda_id", sa.Integer(), nullable=True),
        sa.Column(
            "estado", sa.String(length=15), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insumo_id"],
            ["insumo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["punto_venta_id"],
            ["punto_venta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "insumo_id", "punto_venta_id", "gestor_carga_id", "moneda_id"
        ),
    )
    op.create_table(
        "insumo_punto_venta_precio",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insumo_punto_venta_id", sa.Integer(), nullable=True),
        sa.Column("precio", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("fecha_inicio", sa.DateTime(), nullable=True),
        sa.Column("fecha_fin", sa.DateTime(), nullable=True),
        sa.Column(
            "estado", sa.String(length=15), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["insumo_punto_venta_id"],
            ["insumo_punto_venta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("insumo_punto_venta_id", "precio"),
    )
    op.create_table(
        "camion_semi_neto",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=True),
        sa.Column("camion_id", sa.Integer(), nullable=True),
        sa.Column("semi_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("neto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column(
            "estado", sa.String(length=15), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["camion_id"],
            ["camion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["producto.id"],
        ),
        sa.ForeignKeyConstraint(
            ["semi_id"],
            ["semi.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("camion_id", "semi_id", "producto_id", "gestor_carga_id"),
    )
    op.create_table(
        "orden_carga",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camion_id", sa.Integer(), nullable=True),
        sa.Column("semi_id", sa.Integer(), nullable=True),
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.Column(
            "cantidad_nominada", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("comentarios", sa.Text(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column(
            "estado", sa.String(length=15), server_default="Nuevo", nullable=True
        ),
        sa.Column(
            "orden_carga_estado",
            sa.String(length=25),
            server_default="Pendiente",
            nullable=True,
        ),
        sa.Column(
            "anticipos_liberados",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column("origen_id", sa.Integer(), nullable=True),
        sa.Column("destino_id", sa.Integer(), nullable=True),
        sa.Column("fecha_aceptado", sa.DateTime(), nullable=True),
        sa.Column("fecha_cancelado", sa.DateTime(), nullable=True),
        sa.Column("fecha_conciliado", sa.DateTime(), nullable=True),
        sa.Column("fecha_contabilizado", sa.DateTime(), nullable=True),
        sa.Column("fecha_en_proceso", sa.DateTime(), nullable=True),
        sa.Column("fecha_finalizado", sa.DateTime(), nullable=True),
        sa.Column("fecha_liquidado", sa.DateTime(), nullable=True),
        sa.Column("fecha_nuevo", sa.DateTime(), nullable=True),
        sa.Column("fecha_pendiente", sa.DateTime(), nullable=True),
        sa.Column("fecha_arribado_a_cargar", sa.DateTime(), nullable=True),
        sa.Column("fecha_arribado_a_descargar", sa.DateTime(), nullable=True),
        sa.Column("fecha_cargado", sa.DateTime(), nullable=True),
        sa.Column("fecha_descargado", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["camion_id"],
            ["camion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destino_id"],
            ["centro_operativo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origen_id"],
            ["centro_operativo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["semi_id"],
            ["semi.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orden_carga_anticipo_retirado",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flete_anticipo_id", sa.Integer(), nullable=True),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column("punto_venta_id", sa.Integer(), nullable=True),
        sa.Column("tipo_comprobante_id", sa.Integer(), nullable=True),
        sa.Column("numero_comprobante", sa.String(length=255), nullable=True),
        sa.Column("moneda_id", sa.Integer(), nullable=True),
        sa.Column("monto_retirado", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("observacion", sa.Text(), nullable=True),
        sa.Column("insumo_punto_venta_precio_id", sa.Integer(), nullable=True),
        sa.Column("unidad_id", sa.Integer(), nullable=True),
        sa.Column(
            "cantidad_retirada", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("precio_unitario", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["flete_anticipo_id"],
            ["flete_anticipo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insumo_punto_venta_precio_id"],
            ["insumo_punto_venta_precio.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["punto_venta_id"],
            ["punto_venta.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_comprobante_id"],
            ["tipo_comprobante.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unidad_id"],
            ["unidad.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flete_anticipo_id", "orden_carga_id", "punto_venta_id"),
    )
    op.create_table(
        "orden_carga_anticipo_saldo",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flete_anticipo_id", sa.Integer(), nullable=True),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column("monto_total", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("total_retirado", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("saldo", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["flete_anticipo_id"],
            ["flete_anticipo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flete_anticipo_id", "orden_carga_id"),
    )
    op.create_table(
        "orden_carga_complemento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concepto_id", sa.Integer(), nullable=True),
        sa.Column("detalle", sa.Text(), nullable=True),
        sa.Column(
            "habilitar_cobro_remitente",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "anticipado", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "propietario_monto", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("propietario_moneda_id", sa.Integer(), nullable=True),
        sa.Column("remitente_monto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("remitente_moneda_id", sa.Integer(), nullable=True),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concepto_id"],
            ["tipo_concepto_complemento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["propietario_moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["remitente_moneda_id"],
            ["moneda.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "concepto_id",
            "propietario_moneda_id",
            "propietario_monto",
            "remitente_moneda_id",
            "remitente_monto",
            "orden_carga_id",
        ),
    )
    op.create_table(
        "orden_carga_descuento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concepto_id", sa.Integer(), nullable=True),
        sa.Column("detalle", sa.Text(), nullable=True),
        sa.Column(
            "habilitar_pago_proveedor",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "anticipado", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "propietario_monto", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("propietario_moneda_id", sa.Integer(), nullable=True),
        sa.Column("proveedor_monto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("proveedor_moneda_id", sa.Integer(), nullable=True),
        sa.Column("proveedor_id", sa.Integer(), nullable=True),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column("flete_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concepto_id"],
            ["tipo_concepto_descuento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flete_id"],
            ["flete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["propietario_moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["proveedor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_moneda_id"],
            ["moneda.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "concepto_id",
            "propietario_moneda_id",
            "propietario_monto",
            "proveedor_moneda_id",
            "proveedor_monto",
            "orden_carga_id",
        ),
    )
    op.create_table(
        "orden_carga_remision_destino",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero_documento", sa.String(length=255), nullable=True),
        sa.Column("fecha", sa.DateTime(), nullable=True),
        sa.Column("cantidad", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("foto_documento", sa.String(length=255), nullable=True),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column("unidad_id", sa.Integer(), nullable=True),
        sa.Column("numero_documento_origen", sa.String(length=255), nullable=True),
        sa.Column("destino_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["destino_id"],
            ["centro_operativo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unidad_id"],
            ["unidad.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_documento"),
    )
    op.create_table(
        "orden_carga_remision_origen",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero_documento", sa.String(length=255), nullable=True),
        sa.Column("fecha", sa.DateTime(), nullable=True),
        sa.Column("cantidad", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("foto_documento", sa.String(length=255), nullable=True),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column("unidad_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unidad_id"],
            ["unidad.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_documento"),
    )
    op.add_column("flete", sa.Column("gestor_carga_id", sa.Integer(), nullable=True))
    op.drop_constraint("flete_gestor_cuenta_id_fkey", "flete", type_="foreignkey")
    op.create_foreign_key(None, "flete", "gestor_carga", ["gestor_carga_id"], ["id"])
    op.drop_column("flete", "gestor_cuenta_id")
    op.add_column(
        "flete_anticipo", sa.Column("tipo_insumo_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "flete_anticipo_tipo_id_flete_id_key", "flete_anticipo", type_="unique"
    )
    op.create_unique_constraint(
        None, "flete_anticipo", ["tipo_id", "flete_id", "tipo_insumo_id"]
    )
    op.create_foreign_key(
        None, "flete_anticipo", "tipo_insumo", ["tipo_insumo_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "flete_anticipo", type_="foreignkey")
    op.drop_constraint(None, "flete_anticipo", type_="unique")
    op.create_unique_constraint(
        "flete_anticipo_tipo_id_flete_id_key", "flete_anticipo", ["tipo_id", "flete_id"]
    )
    op.drop_column("flete_anticipo", "tipo_insumo_id")
    op.add_column(
        "flete",
        sa.Column("gestor_cuenta_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "flete", type_="foreignkey")
    op.create_foreign_key(
        "flete_gestor_cuenta_id_fkey",
        "flete",
        "gestor_carga",
        ["gestor_cuenta_id"],
        ["id"],
    )
    op.drop_column("flete", "gestor_carga_id")
    op.drop_table("orden_carga_remision_origen")
    op.drop_table("orden_carga_remision_destino")
    op.drop_table("orden_carga_descuento")
    op.drop_table("orden_carga_complemento")
    op.drop_table("orden_carga_anticipo_saldo")
    op.drop_table("orden_carga_anticipo_retirado")
    op.drop_table("orden_carga")
    op.drop_table("camion_semi_neto")
    op.drop_table("insumo_punto_venta_precio")
    op.drop_table("insumo_punto_venta")
    op.drop_table("insumo")
    op.drop_table("tipo_insumo")
    # ### end Alembic commands ###
