"""empty message

Revision ID: c28f34015a12
Revises: 08175e97884c
Create Date: 2022-04-12 18:20:11.664389

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c28f34015a12"
down_revision = "08175e97884c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movimiento",
        sa.Column(
            "es_editable", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.add_column("movimiento", sa.Column("fecha", sa.DateTime(), nullable=True))
    op.add_column("movimiento", sa.Column("detalle", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movimiento", "detalle")
    op.drop_column("movimiento", "fecha")
    op.drop_column("movimiento", "es_editable")
    # ### end Alembic commands ###
