"""empty message

Revision ID: cec03d4e5025
Revises: ecf70888f51c
Create Date: 2021-10-26 12:19:17.348760

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cec03d4e5025"
down_revision = "ecf70888f51c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rol",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=255), nullable=True),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "user_rol",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["rol.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.add_column("user", sa.Column("gestor_carga_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_user_gestor_carga", "user", "gestor_carga", ["gestor_carga_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_gestor_carga", "user", type_="foreignkey")
    op.drop_column("user", "gestor_carga_id")
    op.drop_table("user_rol")
    op.drop_table("rol")
    # ### end Alembic commands ###
