"""empty message

Revision ID: d7c784d9c284
Revises: 57d00255b20a
Create Date: 2021-11-09 11:24:32.430417

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d7c784d9c284"
down_revision = "57d00255b20a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "punto_venta",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("nombre_corto", sa.String(length=255), nullable=True),
        sa.Column("proveedor_id", sa.Integer(), nullable=True),
        sa.Column("tipo_documento_id", sa.Integer(), nullable=True),
        sa.Column("numero_documento", sa.String(length=255), nullable=True),
        sa.Column("digito_verificador", sa.String(length=2), nullable=True),
        sa.Column("composicion_juridica_id", sa.Integer(), nullable=True),
        sa.Column("logo", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("telefono", sa.String(length=25), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("pagina_web", sa.String(length=255), nullable=True),
        sa.Column("info_complementaria", sa.Text(), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("latitud", sa.DECIMAL(), nullable=True),
        sa.Column("longitud", sa.DECIMAL(), nullable=True),
        sa.Column("ciudad_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ciudad_id"],
            ["ciudad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["composicion_juridica_id"],
            ["composicion_juridica.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["proveedor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_documento_id"],
            ["tipo_documento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo_documento_id", "numero_documento"),
    )
    op.create_table(
        "gestor_carga_punto_venta",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("punto_venta_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["punto_venta_id"],
            ["punto_venta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("punto_venta_id", "gestor_carga_id"),
    )
    op.create_table(
        "punto_venta_contacto_gestor_carga",
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cargo_id", sa.Integer(), nullable=True),
        sa.Column("punto_venta_id", sa.Integer(), nullable=True),
        sa.Column("contacto_id", sa.Integer(), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("alias", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["cargo_id"],
            ["cargo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contacto_id"],
            ["contacto.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["punto_venta_id"],
            ["punto_venta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("punto_venta_id", "contacto_id", "gestor_carga_id"),
    )
    op.add_column(
        "proveedor", sa.Column("info_complementaria", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proveedor", "info_complementaria")
    op.drop_table("punto_venta_contacto_gestor_carga")
    op.drop_table("gestor_carga_punto_venta")
    op.drop_table("punto_venta")
    # ### end Alembic commands ###
