"""empty message

Revision ID: da90d7fbf322
Revises: ed52260128e3
Create Date: 2022-03-09 15:15:08.444473

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "da90d7fbf322"
down_revision = "ed52260128e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tipo_contraparte",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "tipo_documento_relacionado",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "tipo_instrumento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "liquidacion",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo_contraparte_id", sa.Integer(), nullable=True),
        sa.Column("contraparte", sa.String(length=255), nullable=True),
        sa.Column("contraparte_numero_documento", sa.String(length=255), nullable=True),
        sa.Column("fecha_pago_cobro", sa.DateTime(), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("moneda_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_contraparte_id"],
            ["tipo_contraparte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tipo_cuenta",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("tipo_documento_relacionado_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tipo_documento_relacionado_id"],
            ["tipo_documento_relacionado.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "tipo_movimiento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("tipo_documento_relacionado_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tipo_documento_relacionado_id"],
            ["tipo_documento_relacionado.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.create_table(
        "instrumento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("caja_id", sa.Integer(), nullable=True),
        sa.Column("banco_id", sa.Integer(), nullable=True),
        sa.Column("liquidacion_id", sa.Integer(), nullable=True),
        sa.Column("fecha_instrumento", sa.DateTime(), nullable=True),
        sa.Column("credito", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("debito", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column(
            "saldo_confirmado", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("provision", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column(
            "saldo_provisional", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("tipo_instrumento_id", sa.Integer(), nullable=True),
        sa.Column(
            "operacion_estado",
            sa.String(length=255),
            server_default="Emitido",
            nullable=True,
        ),
        sa.Column("operacion_numero_documento", sa.String(length=255), nullable=True),
        sa.Column("operacion_descripcion", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["banco_id"],
            ["banco.id"],
        ),
        sa.ForeignKeyConstraint(
            ["caja_id"],
            ["caja.id"],
        ),
        sa.ForeignKeyConstraint(
            ["liquidacion_id"],
            ["liquidacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_instrumento_id"],
            ["tipo_instrumento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movimiento",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("liquidacion_id", sa.Integer(), nullable=True),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Pendiente", nullable=True
        ),
        sa.Column("tipo_contraparte_id", sa.Integer(), nullable=True),
        sa.Column("contraparte", sa.String(length=255), nullable=True),
        sa.Column("contraparte_numero_documento", sa.String(length=255), nullable=True),
        sa.Column("tipo_documento_relacionado_id", sa.Integer(), nullable=True),
        sa.Column("numero_documento_relacionado", sa.String(length=255), nullable=True),
        sa.Column("cuenta_id", sa.Integer(), nullable=True),
        sa.Column("tipo_movimiento_id", sa.Integer(), nullable=True),
        sa.Column("monto", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("moneda_id", sa.Integer(), nullable=True),
        sa.Column(
            "tipo_cambio_moneda", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("fecha_cambio_moneda", sa.DateTime(), nullable=True),
        sa.Column("anticipo_id", sa.Integer(), nullable=True),
        sa.Column("complemento_id", sa.Integer(), nullable=True),
        sa.Column("descuento_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["anticipo_id"],
            ["orden_carga_anticipo_retirado.id"],
        ),
        sa.ForeignKeyConstraint(
            ["complemento_id"],
            ["orden_carga_complemento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cuenta_id"],
            ["tipo_cuenta.id"],
        ),
        sa.ForeignKeyConstraint(
            ["descuento_id"],
            ["orden_carga_descuento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["liquidacion_id"],
            ["liquidacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moneda_id"],
            ["moneda.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_contraparte_id"],
            ["tipo_contraparte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_documento_relacionado_id"],
            ["tipo_documento_relacionado.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_movimiento_id"],
            ["tipo_movimiento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movimiento")
    op.drop_table("instrumento")
    op.drop_table("tipo_movimiento")
    op.drop_table("tipo_cuenta")
    op.drop_table("liquidacion")
    op.drop_table("tipo_instrumento")
    op.drop_table("tipo_documento_relacionado")
    op.drop_table("tipo_contraparte")
    # ### end Alembic commands ###
