"""empty message

Revision ID: dbfaf827a6a0
Revises: da90d7fbf322
Create Date: 2022-03-14 13:15:27.029003

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dbfaf827a6a0"
down_revision = "da90d7fbf322"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("liquidacion", sa.Column("chofer_id", sa.Integer(), nullable=True))
    op.add_column(
        "liquidacion", sa.Column("gestor_carga_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "liquidacion", sa.Column("propietario_id", sa.Integer(), nullable=True)
    )
    op.add_column("liquidacion", sa.Column("proveedor_id", sa.Integer(), nullable=True))
    op.add_column("liquidacion", sa.Column("remitente_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "liquidacion", "propietario", ["propietario_id"], ["id"]
    )
    op.create_foreign_key(None, "liquidacion", "chofer", ["chofer_id"], ["id"])
    op.create_foreign_key(
        None, "liquidacion", "gestor_carga", ["gestor_carga_id"], ["id"]
    )
    op.create_foreign_key(None, "liquidacion", "proveedor", ["proveedor_id"], ["id"])
    op.create_foreign_key(None, "liquidacion", "remitente", ["remitente_id"], ["id"])
    op.add_column("movimiento", sa.Column("chofer_id", sa.Integer(), nullable=True))
    op.add_column(
        "movimiento", sa.Column("propietario_id", sa.Integer(), nullable=True)
    )
    op.add_column("movimiento", sa.Column("proveedor_id", sa.Integer(), nullable=True))
    op.add_column("movimiento", sa.Column("remitente_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "movimiento", "remitente", ["remitente_id"], ["id"])
    op.create_foreign_key(None, "movimiento", "propietario", ["propietario_id"], ["id"])
    op.create_foreign_key(None, "movimiento", "chofer", ["chofer_id"], ["id"])
    op.create_foreign_key(None, "movimiento", "proveedor", ["proveedor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_column("movimiento", "remitente_id")
    op.drop_column("movimiento", "proveedor_id")
    op.drop_column("movimiento", "propietario_id")
    op.drop_column("movimiento", "chofer_id")
    op.drop_constraint(None, "liquidacion", type_="foreignkey")
    op.drop_constraint(None, "liquidacion", type_="foreignkey")
    op.drop_constraint(None, "liquidacion", type_="foreignkey")
    op.drop_constraint(None, "liquidacion", type_="foreignkey")
    op.drop_constraint(None, "liquidacion", type_="foreignkey")
    op.drop_column("liquidacion", "remitente_id")
    op.drop_column("liquidacion", "proveedor_id")
    op.drop_column("liquidacion", "propietario_id")
    op.drop_column("liquidacion", "gestor_carga_id")
    op.drop_column("liquidacion", "chofer_id")
    # ### end Alembic commands ###
