"""empty message

Revision ID: e0111f8b458a
Revises: c1c7f37ac666
Create Date: 2022-01-31 12:55:29.039169

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e0111f8b458a"
down_revision = "c1c7f37ac666"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orden_carga_anticipo_saldo",
        sa.Column("total_anticipo", sa.Numeric(precision=38, scale=10), nullable=True),
    )
    op.add_column(
        "orden_carga_anticipo_saldo",
        sa.Column(
            "total_complemento", sa.Numeric(precision=38, scale=10), nullable=True
        ),
    )
    op.drop_column("orden_carga_anticipo_saldo", "monto_total")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orden_carga_anticipo_saldo",
        sa.Column(
            "monto_total",
            sa.NUMERIC(precision=38, scale=10),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("orden_carga_anticipo_saldo", "total_complemento")
    op.drop_column("orden_carga_anticipo_saldo", "total_anticipo")
    # ### end Alembic commands ###
