"""generate provision table

Revision ID: e7fe1e4fc1f7
Revises: d9cea90e7162
Create Date: 2025-02-28 11:48:19.369474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7fe1e4fc1f7'
down_revision = 'd9cea90e7162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combinacion',
        sa.Column('created_by', sa.String(length=255), server_default='system', nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chofer_id', sa.Integer(), nullable=True),
        sa.Column('propietario_id', sa.Integer(), nullable=True),
        sa.Column('camion_id', sa.Integer(), nullable=True),
        sa.Column('semi_id', sa.Integer(), nullable=True),
        sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
        sa.Column('comentario', sa.String(length=255), nullable=True),
        sa.Column('gestor_carga_id', sa.Integer(), nullable=True),
        sa.Column('neto', sa.Numeric(precision=38, scale=10), nullable=True),
        sa.ForeignKeyConstraint(['camion_id'], ['camion.id'], ),
        sa.ForeignKeyConstraint(['chofer_id'], ['chofer.id'], ),
        sa.ForeignKeyConstraint(['gestor_carga_id'], ['gestor_carga.id'], ),
        sa.ForeignKeyConstraint(['propietario_id'], ['propietario.id'], ),
        sa.ForeignKeyConstraint(['semi_id'], ['semi.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provision',
        sa.Column('created_by', sa.String(length=255), server_default='system', nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('gestor_carga_id', sa.Integer(), nullable=True),
        sa.Column('orden_carga_id', sa.Integer(), nullable=True),
        sa.Column('estado', sa.String(length=255), server_default='Pendiente', nullable=True),
        sa.Column('tipo_contraparte_id', sa.Integer(), nullable=True),
        sa.Column('contraparte', sa.String(length=255), nullable=True),
        sa.Column('contraparte_numero_documento', sa.String(length=255), nullable=True),
        sa.Column('tipo_documento_relacionado_id', sa.Integer(), nullable=True),
        sa.Column('numero_documento_relacionado', sa.String(length=255), nullable=True),
        sa.Column('cuenta_id', sa.Integer(), nullable=True),
        sa.Column('tipo_movimiento_id', sa.Integer(), nullable=True),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.Column('detalle', sa.Text(), nullable=True),
        sa.Column('tipo_movimiento_info', sa.Text(), nullable=True),
        sa.Column('monto', sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column('moneda_id', sa.Integer(), nullable=True),
        sa.Column('tipo_cambio_moneda', sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column('fecha_cambio_moneda', sa.DateTime(), nullable=True),
        sa.Column('anticipo_id', sa.Integer(), nullable=True),
        sa.Column('complemento_id', sa.Integer(), nullable=True),
        sa.Column('descuento_id', sa.Integer(), nullable=True),
        sa.Column('chofer_id', sa.Integer(), nullable=True),
        sa.Column('propietario_id', sa.Integer(), nullable=True),
        sa.Column('proveedor_id', sa.Integer(), nullable=True),
        sa.Column('remitente_id', sa.Integer(), nullable=True),
        sa.Column('punto_venta_id', sa.Integer(), nullable=True),
        sa.Column('linea_movimiento', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['anticipo_id'], ['orden_carga_anticipo_retirado.id'], ),
        sa.ForeignKeyConstraint(['chofer_id'], ['chofer.id'], ),
        sa.ForeignKeyConstraint(['complemento_id'], ['orden_carga_complemento.id'], ),
        sa.ForeignKeyConstraint(['cuenta_id'], ['tipo_cuenta.id'], ),
        sa.ForeignKeyConstraint(['descuento_id'], ['orden_carga_descuento.id'], ),
        sa.ForeignKeyConstraint(['gestor_carga_id'], ['gestor_carga.id'], ),
        sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id'], ),
        sa.ForeignKeyConstraint(['orden_carga_id'], ['orden_carga.id'], ),
        sa.ForeignKeyConstraint(['propietario_id'], ['propietario.id'], ),
        sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
        sa.ForeignKeyConstraint(['remitente_id'], ['remitente.id'], ),
        sa.ForeignKeyConstraint(['tipo_contraparte_id'], ['tipo_contraparte.id'], ),
        sa.ForeignKeyConstraint(['tipo_documento_relacionado_id'], ['tipo_documento_relacionado.id'], ),
        sa.ForeignKeyConstraint(['tipo_movimiento_id'], ['tipo_movimiento.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column("orden_carga", sa.Column("combinacion_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orden_carga', 'combinacion', ['combinacion_id'], ['id'])


def downgrade():
    op.drop_table('provision')
    op.drop_table('combinacion')

