"""empty message

Revision ID: e912e17117c5
Revises: 232894d29c06
Create Date: 2022-11-18 15:28:35.008020

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e912e17117c5"
down_revision = "232894d29c06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orden_carga", sa.Column("camion_semi_neto_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "orden_carga", "camion_semi_neto", ["camion_semi_neto_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orden_carga", type_="foreignkey")
    op.drop_column("orden_carga", "camion_semi_neto_id")
    # ### end Alembic commands ###
