"""empty message

Revision ID: e949534171d8
Revises: 66424f8d4601
Create Date: 2022-10-20 18:15:14.265455

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e949534171d8"
down_revision = "66424f8d4601"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orden_carga_anticipo_porcentaje",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("porcentaje", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column(
            "porcentaje_minimo", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column("flete_anticipo_id", sa.Integer(), nullable=True),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["flete_anticipo_id"],
            ["flete_anticipo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flete_anticipo_id", "orden_carga_id"),
    )
    op.add_column(
        "orden_carga_anticipo_retirado",
        sa.Column("orden_carga_anticipo_porcentaje_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "orden_carga_anticipo_retirado",
        "orden_carga_anticipo_porcentaje",
        ["orden_carga_anticipo_porcentaje_id"],
        ["id"],
    )
    op.add_column(
        "orden_carga_anticipo_saldo",
        sa.Column("orden_carga_anticipo_porcentaje_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "orden_carga_anticipo_saldo",
        "orden_carga_anticipo_porcentaje",
        ["orden_carga_anticipo_porcentaje_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orden_carga_anticipo_saldo", type_="foreignkey")
    op.drop_column("orden_carga_anticipo_saldo", "orden_carga_anticipo_porcentaje_id")
    op.drop_constraint(None, "orden_carga_anticipo_retirado", type_="foreignkey")
    op.drop_column(
        "orden_carga_anticipo_retirado", "orden_carga_anticipo_porcentaje_id"
    )
    op.drop_table("orden_carga_anticipo_porcentaje")
    # ### end Alembic commands ###
