"""empty message

Revision ID: ecf70888f51c
Revises: 608847d71b87
Create Date: 2021-10-14 13:06:17.691833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf70888f51c'
down_revision = '608847d71b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('composicion_juridica',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('nombre_corto', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('moneda',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('simbolo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('simbolo')
    )
    op.create_table('tipo_documento',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('gestor_carga',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('nombre_corto', sa.String(length=255), nullable=True),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=True),
    sa.Column('numero_documento', sa.String(length=255), nullable=True),
    sa.Column('digito_verificador', sa.String(length=2), nullable=True),
    sa.Column('composicion_juridica_id', sa.Integer(), nullable=True),
    sa.Column('moneda_id', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('pagina_web', sa.String(length=255), nullable=True),
    sa.Column('info_complementaria', sa.Text(), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.DECIMAL(), nullable=True),
    sa.Column('longitud', sa.DECIMAL(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.ForeignKeyConstraint(['composicion_juridica_id'], ['composicion_juridica.id'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipo_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_documento_id', 'numero_documento')
    )
    op.create_table('centro_operativo_contacto_gestor_carga',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('centro_operativo_id', sa.Integer(), nullable=True),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('gestor_carga_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['centro_operativo_id'], ['centro_operativo.id'], ),
    sa.ForeignKeyConstraint(['contacto_id'], ['contacto.id'], ),
    sa.ForeignKeyConstraint(['gestor_carga_id'], ['gestor_carga.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centro_operativo_id', 'contacto_id', 'gestor_carga_id')
    )
    op.create_table('gestor_carga_centro_operativo',
    sa.Column('modified_by', sa.String(length=255), server_default='system', nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centro_operativo_id', sa.Integer(), nullable=True),
    sa.Column('gestor_carga_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), server_default='Activo', nullable=True),
    sa.ForeignKeyConstraint(['centro_operativo_id'], ['centro_operativo.id'], ),
    sa.ForeignKeyConstraint(['gestor_carga_id'], ['gestor_carga.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centro_operativo_id', 'gestor_carga_id')
    )
    op.drop_table('centro_operativo_contacto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centro_operativo_contacto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('centro_operativo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contacto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['centro_operativo_id'], ['centro_operativo.id'], name='centro_operativo_contacto_centro_operativo_id_fkey'),
    sa.ForeignKeyConstraint(['contacto_id'], ['contacto.id'], name='centro_operativo_contacto_contacto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='centro_operativo_contacto_pkey')
    )
    op.drop_table('gestor_carga_centro_operativo')
    op.drop_table('centro_operativo_contacto_gestor_carga')
    op.drop_table('gestor_carga')
    op.drop_table('tipo_documento')
    op.drop_table('moneda')
    op.drop_table('composicion_juridica')
    op.drop_table('cargo')
    # ### end Alembic commands ###
