"""empty message

Revision ID: ed52260128e3
Revises: 17656ae9f551
Create Date: 2022-03-04 16:49:02.497352

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed52260128e3"
down_revision = "17656ae9f551"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banco",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero_cuenta", sa.String(length=255), nullable=True),
        sa.Column("titular", sa.String(length=255), nullable=True),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("moneda_id", sa.Integer(), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("credito", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("debito", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column(
            "saldo_confirmado", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.Column(
            "saldo_provisional", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moneda_id"],
            ["moneda.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_cuenta", "gestor_carga_id"),
    )
    op.create_table(
        "caja",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("gestor_carga_id", sa.Integer(), nullable=True),
        sa.Column("moneda_id", sa.Integer(), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.Column("credito", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("debito", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column(
            "saldo_confirmado", sa.Numeric(precision=38, scale=10), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["gestor_carga_id"],
            ["gestor_carga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moneda_id"],
            ["moneda.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre", "gestor_carga_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("caja")
    op.drop_table("banco")
    # ### end Alembic commands ###
