"""empty message

Revision ID: eff880ff5cac
Revises: 5b79625ee9ca
Create Date: 2022-04-04 16:16:05.855040

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "eff880ff5cac"
down_revision = "5b79625ee9ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instrumento_via",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "estado", sa.String(length=255), server_default="Activo", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("descripcion"),
    )
    op.drop_column("banco", "credito")
    op.drop_column("banco", "debito")
    op.drop_column("caja", "credito")
    op.drop_column("caja", "debito")
    op.add_column("instrumento", sa.Column("via_id", sa.Integer(), nullable=True))
    op.add_column(
        "instrumento",
        sa.Column("numero_referencia", sa.String(length=255), nullable=True),
    )
    op.add_column("instrumento", sa.Column("comentario", sa.Text(), nullable=True))
    op.add_column(
        "instrumento",
        sa.Column(
            "provision_rechazada", sa.Numeric(precision=38, scale=10), nullable=True
        ),
    )
    op.add_column(
        "instrumento", sa.Column("cheque_es_diferido", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "instrumento",
        sa.Column("cheque_fecha_vencimiento", sa.DateTime(), nullable=True),
    )
    op.create_foreign_key(None, "instrumento", "instrumento_via", ["via_id"], ["id"])
    op.drop_column("instrumento", "operacion_numero_documento")
    op.drop_column("instrumento", "operacion_descripcion")
    op.add_column("tipo_instrumento", sa.Column("via_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "tipo_instrumento", "instrumento_via", ["via_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tipo_instrumento", type_="foreignkey")
    op.drop_column("tipo_instrumento", "via_id")
    op.add_column(
        "instrumento",
        sa.Column(
            "operacion_descripcion", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "instrumento",
        sa.Column(
            "operacion_numero_documento",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "instrumento", type_="foreignkey")
    op.drop_column("instrumento", "cheque_fecha_vencimiento")
    op.drop_column("instrumento", "cheque_es_diferido")
    op.drop_column("instrumento", "provision_rechazada")
    op.drop_column("instrumento", "comentario")
    op.drop_column("instrumento", "numero_referencia")
    op.drop_column("instrumento", "via_id")
    op.add_column(
        "caja",
        sa.Column(
            "debito",
            sa.NUMERIC(precision=38, scale=10),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "caja",
        sa.Column(
            "credito",
            sa.NUMERIC(precision=38, scale=10),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "banco",
        sa.Column(
            "debito",
            sa.NUMERIC(precision=38, scale=10),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "banco",
        sa.Column(
            "credito",
            sa.NUMERIC(precision=38, scale=10),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("instrumento_via")
    # ### end Alembic commands ###
