"""empty message

Revision ID: fa8f263a0ca6
Revises: 3c141e8fffd4
Create Date: 2022-06-24 12:04:37.119481

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fa8f263a0ca6"
down_revision = "3c141e8fffd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_permiso")
    op.drop_column("user", "is_activated")
    op.drop_column("user", "last_activity")
    op.drop_column("user", "activated_at")
    op.drop_column("user", "permissions")
    op.drop_column("user", "last_login")
    op.drop_column("user", "last_seen")
    op.drop_column("user", "is_guest")

    op.drop_table("user_rol")
    op.create_table(
        "user_rol",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rol_id"], ["rol.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rol_id", "user_id"),
    )

    op.add_column(
        "permiso",
        sa.Column(
            "is_for_superuser",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permiso", "is_for_superuser")
    op.drop_table("user_rol")
    op.create_table(
        "user_rol",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["rol.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "is_guest",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_seen",
            postgresql.TIMESTAMP(precision=0),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_login",
            postgresql.TIMESTAMP(precision=0),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user", sa.Column("permissions", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "activated_at",
            postgresql.TIMESTAMP(precision=0),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_activity",
            postgresql.TIMESTAMP(precision=0),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "is_activated",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "user_permiso",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("permiso_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["permiso_id"], ["permiso.id"], name="user_permiso_permiso_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_permiso_user_id_fkey"
        ),
    )
    # ### end Alembic commands ###
