"""empty message

Revision ID: fc7b2d1d1f1e
Revises: 0eee5ca9f4f2
Create Date: 2022-02-04 21:01:14.283447

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fc7b2d1d1f1e"
down_revision = "0eee5ca9f4f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orden_carga_estado_historial",
        sa.Column(
            "created_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_by", sa.String(length=255), server_default="system", nullable=True
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("orden_carga_id", sa.Integer(), nullable=True),
        sa.Column(
            "estado", sa.String(length=15), server_default="Nuevo", nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["orden_carga_id"],
            ["orden_carga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("orden_carga_id", "estado"),
    )
    op.drop_column("orden_carga", "fecha_arribado_a_descargar")
    op.drop_column("orden_carga", "fecha_conciliado")
    op.drop_column("orden_carga", "fecha_finalizado")
    op.drop_column("orden_carga", "fecha_cargado")
    op.drop_column("orden_carga", "fecha_cancelado")
    op.drop_column("orden_carga", "fecha_contabilizado")
    op.drop_column("orden_carga", "fecha_nuevo")
    op.drop_column("orden_carga", "fecha_arribado_a_cargar")
    op.drop_column("orden_carga", "fecha_pendiente")
    op.drop_column("orden_carga", "fecha_descargado")
    op.drop_column("orden_carga", "fecha_aceptado")
    op.drop_column("orden_carga", "fecha_liquidado")
    op.drop_column("orden_carga", "fecha_en_proceso")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_en_proceso",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_liquidado",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_aceptado", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_descargado",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_pendiente",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_arribado_a_cargar",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_nuevo", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_contabilizado",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_cancelado",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_cargado", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_finalizado",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_conciliado",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orden_carga",
        sa.Column(
            "fecha_arribado_a_descargar",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("orden_carga_estado_historial")
    # ### end Alembic commands ###
