from sqlalchemy.exc import IntegrityError  # type: ignore
from sqlalchemy.orm import Session  # type: ignore

from app.models import Ciudad, Localidad


def ciudad_argentina_seeds(
    db: Session,
    buenos_aires: Localidad,
    catamarca: Localidad,
    chaco: Localidad,
    chubut: Localidad,
    cordoba: Localidad,
    corrientes: Localidad,
    entre_rios: Localidad,
    formosa: Localidad,
    jujuy: Localidad,
    la_pampa: Localidad,
    la_rioja: Localidad,
    mendoza: Localidad,
    misiones: Localidad,
    neuquen: Localidad,
    rio_negro: Localidad,
    salta: Localidad,
    san_juan: Localidad,
    san_luis: Localidad,
    santa_cruz: Localidad,
    santa_fe: Localidad,
    santiago_del_estero: Localidad,
    tierra_del_fuego: Localidad,
    tucuman: Localidad,
):
    try:
        db.add(Ciudad(nombre="General La Madrid", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Las Heras", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Rodríguez", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Lanús", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Lavalle", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Paz", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Laprida", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Pueyrredón", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General San Martín", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Pilar", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Pergamino", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Nueve de Julio", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Necochea", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Navarro", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Moreno", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Morón", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Pellegrini", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Monte Hermoso", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Merlo", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Pehuajó", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Patagones", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Olavarría", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Monte", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Mercedes", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Marcos Paz", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Magdalena", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Lobos", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Lobería", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Luján", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Lomas de Zamora", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Lincoln", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Leandro N. Alem", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Las Flores", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="La Plata", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="La Matanza", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="La Costa", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Junín", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Hipólito Yrigoyen", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Guaminí", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Tres Lomas", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Tordillo", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Tornquist", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Trenque Lauquen", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Tres Arroyos", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Veinticinco de Mayo", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Vicente López", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Villa Gesell", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Villarino", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Zárate", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Distrito Federal", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Viamonte", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Chivilcoy", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Colón", localidad_id=buenos_aires.id))
        db.add(
            Ciudad(
                nombre="Coronel de Marina Leonardo Rosales",
                localidad_id=buenos_aires.id,
            )
        )
        db.add(Ciudad(nombre="Coronel Dorrego", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Coronel Pringles", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Escobar", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Esteban Echeverría", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Coronel Suárez", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Daireaux", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Dolores", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Sarmiento", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Ensenada", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Florencio Varela", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Alvear", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Arenales", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Belgrano", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Guido", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Adolfo Alsina", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Alvarado", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Juan Madariaga", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Cayetano", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Antonio de Areco", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Andrés de Giles", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Salliqueló", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Saladillo", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Saavedra", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Roque Pérez", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Rivadavia", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Rauch", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Ramallo", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Quilmes", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Rojas", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Puán", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Pinamar", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Salto", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Pila", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Pinto", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Adolfo Gonzales Chaves", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="General Villegas", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Alberti", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Almirante Brown", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Ameghino", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Arrecifes", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Avellaneda", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Ayacucho", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Exaltación de la Cruz", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Azul", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Bahía Blanca", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Balcarce", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Baradero", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Benito Juárez", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Maipú", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Mar Chiquita", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Berazategui", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Bragado", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Brandsen", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Chacabuco", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Berisso", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Bolívar", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Cañuelas", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Campana", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Capitán Sarmiento", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Carlos Casares", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Carlos Tejedor", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Carmen de Areco", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Castelli", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Chascomús", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Fernando (2)", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Isidro", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Nicolás", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Pedro", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Vicente", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Suipacha", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Tandil", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Tapalqué", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Tigre", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Tres de Febrero", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="San Fernando (1)", localidad_id=buenos_aires.id))
        db.add(Ciudad(nombre="Santa Rosa", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Ambato", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Andalgalá", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Ancasti", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Tinogasta", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="El Alto", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Antofagasta de la Sierra", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Belén", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Capayán", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Capital", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Fray Mamerto Esquiú", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="La Paz", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Pomán", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Valle Viejo", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Santa María", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="Paclín", localidad_id=catamarca.id))
        db.add(Ciudad(nombre="General Güemes", localidad_id=chaco.id))
        db.add(Ciudad(nombre="San Fernando", localidad_id=chaco.id))
        db.add(Ciudad(nombre="San Lorenzo", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Sargento Cabral", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Veinticinco de Mayo", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Tapenagá", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Quitilipi", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Fray Justo Santa María de Oro", localidad_id=chaco.id))
        db.add(Ciudad(nombre="General Belgrano", localidad_id=chaco.id))
        db.add(Ciudad(nombre="General Donovan", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Nueve de Julio", localidad_id=chaco.id))
        db.add(Ciudad(nombre="O''Higgins'", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Independencia", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Presidencia de la Plaza", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Libertad", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Libertador General San Martín", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Maipú", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Mayor Luis J. Fontana", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Primero de Mayo", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Doce de Octubre", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Almirante Brown", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Bermejo", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Chacabuco", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Comandante Fernández", localidad_id=chaco.id))
        db.add(Ciudad(nombre="Gastre", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Languiñeo", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Mártires", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Rawson", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Biedma", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Telsen", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Sarmiento", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Gaiman", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Futaleufú", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Cushamen", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Florentino Ameghino", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Escalante", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Tehuelches", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Paso de Indios", localidad_id=chubut.id))
        db.add(Ciudad(nombre="Río Senguer", localidad_id=chubut.id))
        db.add(Ciudad(nombre="San Justo", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="San Javier", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Tercero Arriba", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Río Segundo", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Río Seco", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Pocho", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Minas", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Marcos Juárez", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Juárez Celman", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="San Alberto", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Ischilín", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="General San Martín", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Presidente Roque Sáenz Peña", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Punilla", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Río Cuarto", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Calamuchita", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Capital", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Río Primero", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Colón", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Cruz del Eje", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="General Roca", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Totoral", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Unión", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Sobremonte", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Santa María", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="Tulumba", localidad_id=cordoba.id))
        db.add(Ciudad(nombre="San Luis del Palmar", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Santo Tomé", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Sauce", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Lavalle", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Goya", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="San Martín", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="General Paz", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Ituzaingó", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Itatí", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="General Alvear", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Esquina", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="San Miguel", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Curuzú Cuatiá", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Concepción", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Empedrado", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Capital", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Berón de Astrada", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Bella Vista", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Mercedes", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="San Roque", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Monte Caseros", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="San Cosme", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Paso de los Libres", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Mburucuyá", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Saladas", localidad_id=corrientes.id))
        db.add(Ciudad(nombre="Concordia", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Colón", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Diamante", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Federación", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Federal", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Feliciano", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Gualeguaychú", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Gualeguay", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Isla", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Islas del Ibicuy", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="La Paz", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Nogoyá", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Paraná", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Tala", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Uruguay", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Victoria", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Villaguay", localidad_id=entre_rios.id))
        db.add(Ciudad(nombre="Pilagás", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Pilcomayo", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Pirané", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Ramón Lista", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Matacos", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Laishi", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Bermejo", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Formosa", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Patiño", localidad_id=formosa.id))
        db.add(Ciudad(nombre="Ledesma", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Tilcara", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Santa Bárbara", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Yavi", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="San Pedro", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="San Antonio", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Rinconada", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Palpalá", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Humahuaca", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="El Carmen", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Cochinoca", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Capital", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Valle Grande", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Tumbaya", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Susques", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Santa Catalina", localidad_id=jujuy.id))
        db.add(Ciudad(nombre="Conhelo", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Hucal", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Guatraché", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Curacó", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Puelén", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Chical Có", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Chapaleufú", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Chalileo", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Catriló", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Lihuel Calel", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Capital", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Caleu Caleu", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Utracán", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Trenel", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Atreucó", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Realicó", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Toay", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Limay Mahuida", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Maracó", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Loventué", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Rancul", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="Quemú Quemú", localidad_id=la_pampa.id))
        db.add(Ciudad(nombre="General Ocampo", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Rosario Vera Peñaloza", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Sanagasta", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Independencia", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="General San Martín", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="General Lamadrid", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Coronel Felipe Varela", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="General Juan Facundo Quiroga", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="General Belgrano", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Chilecito", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Chamical", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Castro Barros", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Famatina", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Capital", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="San Blas de los Sauces", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="Vinchina", localidad_id=la_rioja.id))
        db.add(
            Ciudad(nombre="General Angel Vicente Peñaloza", localidad_id=la_rioja.id)
        )
        db.add(Ciudad(nombre="Arauco", localidad_id=la_rioja.id))
        db.add(Ciudad(nombre="La Paz", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Tupungato", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="San Carlos", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Rivadavia", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Capital", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="General Alvear", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Godoy Cruz", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Guaymallén", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Junín", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Las Heras", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Lavalle", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Luján de Cuyo", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Maipú", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Malargüe", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="San Martín", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="San Rafael", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Santa Rosa", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Tunuyán", localidad_id=mendoza.id))
        db.add(Ciudad(nombre="Guaraní", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Iguazú", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Leandro N. Alem", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Oberá", localidad_id=misiones.id))
        db.add(Ciudad(nombre="San Ignacio", localidad_id=misiones.id))
        db.add(Ciudad(nombre="San Javier", localidad_id=misiones.id))
        db.add(Ciudad(nombre="San Pedro", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Apóstoles", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Eldorado", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Libertador General San Martín", localidad_id=misiones.id))
        db.add(Ciudad(nombre="General Manuel Belgrano", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Cainguás", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Candelaria", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Concepción", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Capital", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Veinticinco de Mayo", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Montecarlo", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Catán Lil", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Zapala", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Picunches", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Los Lagos", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Picún Leufú", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Pehuenches", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Minas", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Lacar", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Confluencia", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Collón Curá", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Huiliches", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Chos Malal", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Aluminé", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Añelo", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Ñorquín", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Loncopué", localidad_id=neuquen.id))
        db.add(Ciudad(nombre="Ñorquinco", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Adolfo Alsina", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Avellaneda", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Bariloche", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Conesa", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="El Cuy", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="General Roca", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Nueve de Julio", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Pichi Mahuida", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Veinticinco de Mayo", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Pilcaniyeu", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="San Antonio", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Valcheta", localidad_id=rio_negro.id))
        db.add(Ciudad(nombre="Los Andes", localidad_id=salta.id))
        db.add(Ciudad(nombre="Iruya", localidad_id=salta.id))
        db.add(Ciudad(nombre="La Poma", localidad_id=salta.id))
        db.add(Ciudad(nombre="Chicoana", localidad_id=salta.id))
        db.add(Ciudad(nombre="Capital", localidad_id=salta.id))
        db.add(Ciudad(nombre="Cerrillos", localidad_id=salta.id))
        db.add(Ciudad(nombre="General Güemes", localidad_id=salta.id))
        db.add(Ciudad(nombre="General José de San Martín", localidad_id=salta.id))
        db.add(Ciudad(nombre="Guachipas", localidad_id=salta.id))
        db.add(Ciudad(nombre="La Caldera", localidad_id=salta.id))
        db.add(Ciudad(nombre="La Candelaria", localidad_id=salta.id))
        db.add(Ciudad(nombre="Rivadavia", localidad_id=salta.id))
        db.add(Ciudad(nombre="La Viña", localidad_id=salta.id))
        db.add(Ciudad(nombre="Santa Victoria", localidad_id=salta.id))
        db.add(Ciudad(nombre="Metán", localidad_id=salta.id))
        db.add(Ciudad(nombre="Molinos", localidad_id=salta.id))
        db.add(Ciudad(nombre="Orán", localidad_id=salta.id))
        db.add(Ciudad(nombre="Rosario de la Frontera", localidad_id=salta.id))
        db.add(Ciudad(nombre="Rosario de Lerma", localidad_id=salta.id))
        db.add(Ciudad(nombre="San Carlos", localidad_id=salta.id))
        db.add(Ciudad(nombre="Anta", localidad_id=salta.id))
        db.add(Ciudad(nombre="Cachi", localidad_id=salta.id))
        db.add(Ciudad(nombre="Cafayate", localidad_id=salta.id))
        db.add(Ciudad(nombre="Angaco", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Rivadavia", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Iglesia", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Veinticinco de Mayo", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Zonda", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Jáchal", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Albardón", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="San Martín", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Calingasta", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Santa Lucía", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Pocito", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Chimbas", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Capital", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Caucete", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Rawson", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Sarmiento", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Ullum", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="Valle Fértil", localidad_id=san_juan.id))
        db.add(Ciudad(nombre="La Capital", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="Gobernador Dupuy", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="Libertador General San Martín", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="General Pedernera", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="Coronel Pringles", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="Belgrano", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="Ayacucho", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="Junín", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="Chacabuco", localidad_id=san_luis.id))
        db.add(Ciudad(nombre="Lago Buenos Aires", localidad_id=santa_cruz.id))
        db.add(Ciudad(nombre="Corpen Aike", localidad_id=santa_cruz.id))
        db.add(Ciudad(nombre="Deseado", localidad_id=santa_cruz.id))
        db.add(Ciudad(nombre="Güer Aike", localidad_id=santa_cruz.id))
        db.add(Ciudad(nombre="Magallanes", localidad_id=santa_cruz.id))
        db.add(Ciudad(nombre="Rió Chico", localidad_id=santa_cruz.id))
        db.add(Ciudad(nombre="Lago Argentino", localidad_id=santa_cruz.id))
        db.add(Ciudad(nombre="General López", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Garay", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Constitución", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Caseros", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Belgrano", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Castellanos", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Rosario", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Nueve de Julio", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="San Martín", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="San Lorenzo", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Vera", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="San Justo", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="San Jerónimo", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="San Javier", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Las Colonias", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="San Cristóbal", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="La Capital", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Iriondo", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="General Obligado", localidad_id=santa_fe.id))
        db.add(Ciudad(nombre="Guasayán", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Sarmiento", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="San Martín", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Salavina", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Rió Hondo", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Jiménez", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Copo", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Choya", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Figueroa", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Banda", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Avellaneda", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Capital", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Silípica", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="General Taboada", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Robles", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Mitre", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Moreno", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Juan Felipe Ibarra", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Atamisqui", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Belgrano", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Alberdi", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Aguirre", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Loreto", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Quebrachos", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Rivadavia", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Ojo de Agua", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Pellegrini", localidad_id=santiago_del_estero.id))
        db.add(Ciudad(nombre="Rió Grande", localidad_id=tierra_del_fuego.id))
        db.add(Ciudad(nombre="Ushuaia", localidad_id=tierra_del_fuego.id))
        db.add(Ciudad(nombre="Monteros", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Chicligasta", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Lules", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Cruz Alta", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Rió Chico", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Capital", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Famaillá", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Tafí del Valle", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Burruyacú", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Graneros", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Juan B. Alberdi", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="La Cocha", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Leales", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Yerba Buena", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Trancas", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Tafí Viejo", localidad_id=tucuman.id))
        db.add(Ciudad(nombre="Simoca", localidad_id=tucuman.id))
        db.commit()
    except IntegrityError:
        db.rollback()
