from sqlalchemy.exc import IntegrityError  # type: ignore
from sqlalchemy.orm import Session  # type: ignore

from app.models import Ciudad, Localidad


def ciudad_paraguay_seeds(
    db: Session,
    alto_paraguay: Localidad,
    alto_parana: Localidad,
    amambay: Localidad,
    boqueron: Localidad,
    caaguazu: Localidad,
    caazapa: Localidad,
    canindeyu: Localidad,
    central: Localidad,
    concepcion: Localidad,
    cordillera: Localidad,
    guaira: Localidad,
    itapua: Localidad,
    misiones: Localidad,
    neembucu: Localidad,
    paraguari: Localidad,
    presidente_hayes: Localidad,
    san_pedro: Localidad,
):
    try:
        db.add(Ciudad(nombre="La Victoria", localidad_id=alto_paraguay.id))
        db.add(Ciudad(nombre="Fuerte Olimpo", localidad_id=alto_paraguay.id))
        db.add(Ciudad(nombre="Mayor Pablo Lagerenza", localidad_id=alto_paraguay.id))
        db.add(
            Ciudad(nombre="Doctor Juan Leon Mallorquin", localidad_id=alto_parana.id)
        )
        db.add(Ciudad(nombre="Yguazu", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Santa Rosa del Monday", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Santa Rita", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="San Cristobal", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="San Alberto", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Naranjal", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Hernandarias", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Itakyry", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Los Cedrales", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Ciudad del Este", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Minga Guazu", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Minga Pora", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Ñacunday", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Mbaracayu", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Juan Emilio O'Leary", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Presidente Franco", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Domingo Martinez de Irala", localidad_id=alto_parana.id))
        db.add(Ciudad(nombre="Capitan Bado", localidad_id=amambay.id))
        db.add(Ciudad(nombre="Pedro Juan Caballero", localidad_id=amambay.id))
        db.add(Ciudad(nombre="Bella Vista", localidad_id=amambay.id))
        db.add(Ciudad(nombre="General Eugenio A. Garay", localidad_id=boqueron.id))
        db.add(
            Ciudad(nombre="Mariscal Jose Felix Estigarribia", localidad_id=boqueron.id)
        )
        db.add(Ciudad(nombre="Doctor Pedro P. Peña", localidad_id=boqueron.id))
        db.add(Ciudad(nombre="Yhu", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Repatriacion", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="San Jose de los Arroyos", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Raul Arsenio Oviedo", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Jose Domingo Ocampos", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="R. I. 3 Corrales", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Santa Rosa del Mbutuy", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Caaguazu", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Carayao", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Coronel Oviedo", localidad_id=caaguazu.id))
        db.add(
            Ciudad(nombre="Doctor J. Eulogio Estigarribia", localidad_id=caaguazu.id)
        )
        db.add(
            Ciudad(nombre="Mariscal Francisco Solano Lopez", localidad_id=caaguazu.id)
        )
        db.add(Ciudad(nombre="La Pastora", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Doctor Cecilio Baez", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="3 de Febrero", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Doctor Juan Manuel Frutos", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Nueva Londres", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Simon Bolivar", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="San Joaquin", localidad_id=caaguazu.id))
        db.add(Ciudad(nombre="Caazapa", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="Doctor Moises S. Bertoni", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="Yuty", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="General Higinio Morinigo", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="Emboscada (Caazapa)", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="Fulgencio Yegros", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="Manuel A. Maciel", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="Abai", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="San Juan Nepomuceno", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="Tavai", localidad_id=caazapa.id))
        db.add(Ciudad(nombre="General Francisco C. Alvarez", localidad_id=canindeyu.id))
        db.add(Ciudad(nombre="Ypejhu", localidad_id=canindeyu.id))
        db.add(Ciudad(nombre="Villa Ygatimi", localidad_id=canindeyu.id))
        db.add(Ciudad(nombre="Itanara", localidad_id=canindeyu.id))
        db.add(Ciudad(nombre="Corpus Christi", localidad_id=canindeyu.id))
        db.add(Ciudad(nombre="Villa San Isidro Curuguaty", localidad_id=canindeyu.id))
        db.add(Ciudad(nombre="Salto del Guaira", localidad_id=canindeyu.id))
        db.add(Ciudad(nombre="San Lorenzo", localidad_id=central.id))
        db.add(Ciudad(nombre="Asunción", localidad_id=central.id))
        db.add(Ciudad(nombre="Villa Elisa", localidad_id=central.id))
        db.add(Ciudad(nombre="Ita", localidad_id=central.id))
        db.add(Ciudad(nombre="Itaugua", localidad_id=central.id))
        db.add(Ciudad(nombre="Juan Augusto Saldivar", localidad_id=central.id))
        db.add(Ciudad(nombre="Limpio", localidad_id=central.id))
        db.add(Ciudad(nombre="Luque", localidad_id=central.id))
        db.add(Ciudad(nombre="San Antonio", localidad_id=central.id))
        db.add(Ciudad(nombre="Nueva Italia", localidad_id=central.id))
        db.add(Ciudad(nombre="Capiata", localidad_id=central.id))
        db.add(Ciudad(nombre="Mariano Roque Alonso", localidad_id=central.id))
        db.add(Ciudad(nombre="Ypane", localidad_id=central.id))
        db.add(Ciudad(nombre="Ypacarai", localidad_id=central.id))
        db.add(Ciudad(nombre="Guarambare", localidad_id=central.id))
        db.add(Ciudad(nombre="Villeta", localidad_id=central.id))
        db.add(Ciudad(nombre="Aregua", localidad_id=central.id))
        db.add(Ciudad(nombre="Lambare", localidad_id=central.id))
        db.add(Ciudad(nombre="Fernando de la Mora", localidad_id=central.id))
        db.add(Ciudad(nombre="Ñemby", localidad_id=central.id))
        db.add(Ciudad(nombre="Horqueta", localidad_id=concepcion.id))
        db.add(Ciudad(nombre="San Carlos", localidad_id=concepcion.id))
        db.add(Ciudad(nombre="Concepcion", localidad_id=concepcion.id))
        db.add(Ciudad(nombre="Loreto", localidad_id=concepcion.id))
        db.add(Ciudad(nombre="Yby Yau", localidad_id=concepcion.id))
        db.add(Ciudad(nombre="San Lazaro", localidad_id=concepcion.id))
        db.add(Ciudad(nombre="Belen", localidad_id=concepcion.id))
        db.add(Ciudad(nombre="Arroyos y Esteros", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Isla Pucu", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Eusebio Ayala", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Emboscada", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Atyra", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Mbocayaty del Yhaguy", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Nueva Colombia", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Piribebuy", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Primero de Marzo", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="San Jose Obrero", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Santa Elena", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Tobati", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Caraguatay", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Valenzuela", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Caacupe", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="San Bernardino", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Itacurubi de la Cordillera", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Juan de Mena", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Altos", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="Loma Grande", localidad_id=cordillera.id))
        db.add(Ciudad(nombre="General Eugenio A. Garay", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Independencia", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Itape", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Iturbe", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Jose A. Fassardi", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Mbocayaty del Guaira", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Ñumi", localidad_id=guaira.id))
        db.add(Ciudad(nombre="San Salvador", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Villarrica", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Borja", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Felix Perez Cardozo", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Natalicio Talavera", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Capitan Mauricio Jose Troche", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Yataity del Guaira", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Coronel Martinez", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Doctor Botrell", localidad_id=guaira.id))
        db.add(Ciudad(nombre="Coronel Bogado", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Encarnacion", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Edelira", localidad_id=itapua.id))
        db.add(Ciudad(nombre="San Juan del Parana", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Carmen del Parana", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Bella Vista", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Cambyreta", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Alto Vera", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Capitan Meza", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Capitan Miranda", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Carlos Antonio Lopez", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Jesus", localidad_id=itapua.id))
        db.add(Ciudad(nombre="La Paz", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Jose Leandro Oviedo", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Mayor Julio D. Otaño", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Nueva Alborada", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Natalio", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Hohenau", localidad_id=itapua.id))
        db.add(Ciudad(nombre="General Delgado", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Obligado", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Fram", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Pirapo", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Yatytay", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Trinidad", localidad_id=itapua.id))
        db.add(Ciudad(nombre="San Cosme y Damian", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Tomas Romero Pereira", localidad_id=itapua.id))
        db.add(Ciudad(nombre="General Artigas", localidad_id=itapua.id))
        db.add(Ciudad(nombre="San Rafael del Parana", localidad_id=itapua.id))
        db.add(Ciudad(nombre="San Pedro del Parana", localidad_id=itapua.id))
        db.add(Ciudad(nombre="Santa Maria", localidad_id=misiones.id))
        db.add(
            Ciudad(nombre="San Juan Bautista de las Misiones", localidad_id=misiones.id)
        )
        db.add(Ciudad(nombre="San Miguel", localidad_id=misiones.id))
        db.add(Ciudad(nombre="San Patricio", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Ayolas", localidad_id=misiones.id))
        db.add(Ciudad(nombre="San Ignacio", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Yabebyry", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Villa Florida", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Santiago", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Santa Rosa", localidad_id=misiones.id))
        db.add(Ciudad(nombre="Villalbin", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Laureles", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Humaita", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Isla Umbu", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Mayor Jose J. Martinez", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Desmochados", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Alberdi", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Tacuaras", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Villa Franca", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Villa Oliva", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Cerrito", localidad_id=neembucu.id))
        db.add(
            Ciudad(nombre="San Juan Bautista del Ñeembucu", localidad_id=neembucu.id)
        )
        db.add(Ciudad(nombre="General Jose Eduvigis Diaz", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Guazu Cua", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Pilar", localidad_id=neembucu.id))
        db.add(Ciudad(nombre="Paso de Patria", localidad_id=neembucu.id))
        db.add(
            Ciudad(nombre="San Roque Gonzolez de Santa Cruz", localidad_id=paraguari.id)
        )
        db.add(Ciudad(nombre="General Bernardino Caballero", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Ybytimi", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Ybycui", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Tebicuarymi", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Sapucai", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Yaguaron", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Quyquyho", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Quiindy", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Paraguari", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Mbuyapey", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="La Colmena", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Escobar", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Caapucu", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Acahay", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Pirayu", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Carapegua", localidad_id=paraguari.id))
        db.add(Ciudad(nombre="Pozo Colorado", localidad_id=presidente_hayes.id))
        db.add(Ciudad(nombre="Puerto Pinasco", localidad_id=presidente_hayes.id))
        db.add(Ciudad(nombre="Villa Hayes", localidad_id=presidente_hayes.id))
        db.add(Ciudad(nombre="Benjamin Aceval", localidad_id=presidente_hayes.id))
        db.add(Ciudad(nombre="25 de Diciembre", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Villa del Rosario", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Itacurubi del Rosario", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Union", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Tacuati", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="San Pedro del Ycuamandyyu", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Lima", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Nueva Germania", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="San Estanislao", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="General Elizardo Aquino", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="San Pablo", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="General Isidoro Resquin", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Chore", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Antequera", localidad_id=san_pedro.id))
        db.add(Ciudad(nombre="Yataity del Norte", localidad_id=san_pedro.id))
        db.commit()
    except IntegrityError:
        db.rollback()
