# debe importarse para que alembic pueda detectar y crear las tablas
from app import audits  # noqa
from app.database import Base  # noqa

from .banco import Banco  # noqa
from .caja import Caja  # noqa
from .camion import Camion  # noqa
from .camion_semi_neto import CamionSemiNeto  # noqa
from .cargo import Cargo  # noqa
from .centro_operativo import CentroOperativo  # noqa
from .centro_operativo_clasificacion import CentroOperativoClasificacion  # noqa
from .centro_operativo_contacto_gestor_carga import (  # noqa
    CentroOperativoContactoGestorCarga,
)
from .chofer import Chofer  # noqa
from .ciudad import Ciudad  # noqa
from .color import Color  # noqa
from .composicion_juridica import ComposicionJuridica  # noqa
from .contacto import Contacto  # noqa
from .ente_emisor_automotor import EnteEmisorAutomotor  # noqa
from .ente_emisor_transporte import EnteEmisorTransporte  # noqa
from .flete import Flete  # noqa
from .flete_anticipo import FleteAnticipo  # noqa
from .flete_complemento import FleteComplemento  # noqa
from .flete_descuento import FleteDescuento  # noqa
from .gestor_carga import GestorCarga  # noqa
from .gestor_carga_centro_operativo import GestorCargaCentroOperativo  # noqa
from .gestor_carga_chofer import GestorCargaChofer  # noqa
from .gestor_carga_propietario import GestorCargaPropietario  # noqa
from .gestor_carga_proveedor import GestorCargaProveedor  # noqa
from .gestor_carga_punto_venta import GestorCargaPuntoVenta  # noqa
from .gestor_carga_remitente import GestorCargaRemitente  # noqa
from .instrumento import Instrumento  # noqa
from .instrumento_via import InstrumentoVia  # noqa
from .insumo import Insumo  # noqa
from .insumo_punto_venta import InsumoPuntoVenta  # noqa
from .insumo_punto_venta_precio import InsumoPuntoVentaPrecio  # noqa
from .liquidacion import Liquidacion  # noqa
from .localidad import Localidad  # noqa
from .marca_camion import MarcaCamion  # noqa
from .marca_semi import MarcaSemi  # noqa
from .moneda import Moneda  # noqa
from .movimiento import Movimiento  # noqa
from .orden_carga import OrdenCarga  # noqa
from .orden_carga_anticipo_retirado import OrdenCargaAnticipoRetirado  # noqa
from .orden_carga_anticipo_saldo import OrdenCargaAnticipoSaldo  # noqa
from .orden_carga_complemento import OrdenCargaComplemento  # noqa
from .orden_carga_descuento import OrdenCargaDescuento  # noqa
from .orden_carga_estado_historial import OrdenCargaEstadoHistorial  # noqa
from .orden_carga_remision_destino import OrdenCargaRemisionDestino  # noqa
from .orden_carga_remision_origen import OrdenCargaRemisionOrigen  # noqa
from .pais import Pais  # noqa
from .permiso import Permiso  # noqa
from .producto import Producto  # noqa
from .propietario import Propietario  # noqa
from .propietario_contacto_gestor_carga import PropietarioContactoGestorCarga  # noqa
from .proveedor import Proveedor  # noqa
from .proveedor_contacto_gestor_carga import ProveedorContactoGestorCarga  # noqa
from .punto_venta import PuntoVenta  # noqa
from .punto_venta_contacto_gestor_carga import PuntoVentaContactoGestorCarga  # noqa
from .remitente import Remitente  # noqa
from .remitente_contacto_gestor_carga import RemitenteContactoGestorCarga  # noqa
from .rol import Rol  # noqa
from .semi import Semi  # noqa
from .semi_clasificacion import SemiClasificacion  # noqa
from .tipo_anticipo import TipoAnticipo  # noqa
from .tipo_camion import TipoCamion  # noqa
from .tipo_carga import TipoCarga  # noqa
from .tipo_comprobante import TipoComprobante  # noqa
from .tipo_concepto_complemento import TipoConceptoComplemento  # noqa
from .tipo_concepto_descuento import TipoConceptoDescuento  # noqa
from .tipo_contraparte import TipoContraparte  # noqa
from .tipo_cuenta import TipoCuenta  # noqa
from .tipo_documento import TipoDocumento  # noqa
from .tipo_documento_relacionado import TipoDocumentoRelacionado  # noqa
from .tipo_instrumento import TipoInstrumento  # noqa
from .tipo_insumo import TipoInsumo  # noqa
from .tipo_movimiento import TipoMovimiento  # noqa
from .tipo_persona import TipoPersona  # noqa
from .tipo_registro import TipoRegistro  # noqa
from .tipo_semi import TipoSemi  # noqa
from .unidad import Unidad  # noqa
from .user import User  # noqa
