from enum import Enum


class CodigoRolEnum(Enum):
    ADMIN_ICARGO = "ADMIN_ICARGO"
    ADMIN_GESTOR_CARGA = "ADMIN_GESTOR_CARGA"
    SUPLENTE_GESTOR_CARGA = "SUPLENTE_GESTOR_CARGA"
    ADMIN_APP_PROVEEDOR = "ADMIN_APP_PROVEEDOR"
    USUARIO_APP_PROVEEDOR = "USUARIO_APP_PROVEEDOR"
